In [1]:
import requests
import random
import pandas as pd

# Caso práctico: Integración y explotación de datos mediante APIs

## Contexto

El equipo de análisis de datos necesita incorporar información procedente de diferentes fuentes externas para complementar los datos internos de la organización.

Como analista de datos, tendrás que trabajar con APIs REST, comprender las respuestas de los servicios, gestionar diferentes tipos de peticiones HTTP y transformar los datos obtenidos en estructuras que puedan utilizarse posteriormente para su análisis.

El objetivo final es adquirir una primera experiencia en un flujo habitual de trabajo de datos:

API → extracción → validación → transformación → DataFrame → almacenamiento

## 1. Exploración y gestión de una API de laboratorio

Para familiarizarte con el consumo de APIs REST, comenzarás trabajando con una API de pruebas que simula el comportamiento de un servicio real.

El equipo quiere comprobar que eres capaz de consultar diferentes recursos, interpretar las respuestas del servidor y realizar operaciones básicas sobre los datos.

Durante esta fase deberás trabajar con información relacionada con:

- Publicaciones.
- Usuarios.
- Tareas.

Además de recuperar información, se plantea un escenario en el que tendrás que gestionar diferentes situaciones habituales al trabajar con APIs:

- Comprobar que una petición se ha realizado correctamente.
- Identificar qué ocurre cuando se solicita un recurso que no existe.
- Crear una nueva publicación.
- Modificar parcialmente información existente.
- Eliminar una publicación.

### Objetivo de negocio

Demostrar que eres capaz de interactuar con un servicio externo y distinguir entre operaciones de consulta y operaciones de modificación, así como interpretar correctamente las respuestas del servidor.

In [2]:
# Creamos los endpoints que vamos a utilizar
endpoints = ["posts", "users", "todos"]

data = {}

for endpoint in endpoints:
    url = "https://jsonplaceholder.typicode.com/" + endpoint

    response = requests.get(url)
    # mostramos el código de estado de cada petición
    print(f'Status code response for /{endpoint}: {response.status_code}')

    data[endpoint] = response.json()

Status code response for /posts: 200
Status code response for /users: 200
Status code response for /todos: 200

In [3]:
# Mostramos la cantidad total de cada recurso

for endpoint in endpoints:
    print(f'Elements in data["{endpoint}"]: {len(data[endpoint])}')

Elements in data["posts"]: 100
Elements in data["users"]: 10
Elements in data["todos"]: 200

In [4]:
# Hacemos una petición a una publicación inexistente
response = requests.get("https://jsonplaceholder.typicode.com/publicacioninexistente")

response.status_code

404

In [5]:
# Analizamos cómo están compuestos los posts
data['posts'][0]

{'userId': 1,
 'id': 1,
 'title': 'sunt aut facere repellat provident occaecati excepturi optio reprehenderit',
 'body': 'quia et suscipit\nsuscipit recusandae consequuntur expedita et cum\nreprehenderit molestiae ut ut quas totam\nnostrum rerum est autem sunt rem eveniet architecto'}

In [6]:
# Hacemos una petición POST para crear una nueva publicación ficticia
url = "https://jsonplaceholder.typicode.com/posts"

new_post = {
    "userId": random.randint(1, 10),
    "id": data['posts'][-1]['id']+1,
    "title": "titulum inventatum",
    "body": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."
}

response = requests.post(url, json=new_post)

# Mostramos la respuesta JSON
print(response.json())

# Mostramos el código de estado
print(response.status_code)
print(response)

{'userId': 6, 'id': 101, 'title': 'titulum inventatum', 'body': 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.'}
201
<Response [201]>

In [7]:
# Hacemos una petición PATCH para modifficar parcialmente una publicación existente
url = "https://jsonplaceholder.typicode.com/posts/1"

data = {
    "title": "novum titulum"
}

response = requests.patch(
    url,
    json=data
)

# Mostramos la respuesta JSON
print(response.json())

# Mostramos el código de estado
print(response.status_code)

{'userId': 1, 'id': 1, 'title': 'novum titulum', 'body': 'quia et suscipit\nsuscipit recusandae consequuntur expedita et cum\nreprehenderit molestiae ut ut quas totam\nnostrum rerum est autem sunt rem eveniet architecto'}
200

In [8]:
# Hacemos una petición DELETE para borrar una publicación existente

response = requests.delete(url)

# Mostramos la respuesta JSON
print(response.json())

# Mostramos el código de estado
print(response.status_code)

{}
200

################################################################

## Integración con una API pública real

Una vez familiarizado con una API de laboratorio, el equipo quiere dar un paso más y trabajar con una fuente de datos pública real.

Deberás seleccionar una API pública que pueda aportar información potencialmente útil para un proyecto de análisis de datos y estudiar cómo está estructurada antes de comenzar a consumirla.

El objetivo será identificar qué información proporciona el servicio, qué recursos están disponibles y qué posibilidades ofrece para limitar o personalizar las consultas.

Posteriormente realizarás una primera extracción de datos y transformarás la respuesta obtenida en un DataFrame de pandas, dejándolo preparado para posteriores procesos de análisis y exploración.

### Objetivo de negocio

Evaluar la capacidad para incorporar una fuente de datos externa al flujo de trabajo de análisis, entendiendo previamente qué información proporciona y cómo puede utilizarse.

Esta fase representa un escenario habitual en proyectos de datos: antes de incorporar una API a un proceso ETL, el analista debe conocer la estructura, posibilidades y limitaciones de la fuente.

In [9]:
# Utilizaremos la API de Frankfurter

url = "https://api.frankfurter.dev/v2/rates"
response = requests.get(url)

print(response)
response.json()

<Response [200]>

[{'date': '2026-08-18', 'base': 'EUR', 'quote': 'AED', 'rate': 4.2542},
 {'date': '2026-08-18', 'base': 'EUR', 'quote': 'AFN', 'rate': 75.495},
 {'date': '2026-08-18', 'base': 'EUR', 'quote': 'ALL', 'rate': 92.64},
 {'date': '2026-08-18', 'base': 'EUR', 'quote': 'AMD', 'rate': 423.38},
 {'date': '2026-08-18', 'base': 'EUR', 'quote': 'ANG', 'rate': 2.0735},
 {'date': '2026-08-17', 'base': 'EUR', 'quote': 'AOA', 'rate': 1061.61},
 {'date': '2026-08-18', 'base': 'EUR', 'quote': 'ARS', 'rate': 1723.69},
 {'date': '2026-08-18', 'base': 'EUR', 'quote': 'AUD', 'rate': 1.6299},
 {'date': '2026-08-17', 'base': 'EUR', 'quote': 'AWG', 'rate': 2.0722},
 {'date': '2026-08-18', 'base': 'EUR', 'quote': 'AZN', 'rate': 1.9681},
 {'date': '2026-08-18', 'base': 'EUR', 'quote': 'BAM', 'rate': 1.9558},
 {'date': '2026-08-18', 'base': 'EUR', 'quote': 'BBD', 'rate': 2.3611},
 {'date': '2026-08-18', 'base': 'EUR', 'quote': 'BDT', 'rate': 142.15},
 {'date': '2026-08-18', 'base': 'EUR', 'quote': 'BHD', 'rate': 0.43556},
 {'date': '2026-08-18', 'base': 'EUR', 'quote': 'BIF', 'rate': 3471.86},
 {'date': '2026-08-17', 'base': 'EUR', 'quote': 'BMD', 'rate': 1.1584},
 {'date': '2026-08-18', 'base': 'EUR', 'quote': 'BND', 'rate': 1.4795},
 {'date': '2026-08-18', 'base': 'EUR', 'quote': 'BOB', 'rate': 13.4364},
 {'date': '2026-08-18', 'base': 'EUR', 'quote': 'BRL', 'rate': 6.0347},
 {'date': '2026-08-18', 'base': 'EUR', 'quote': 'BSD', 'rate': 1.1731},
 {'date': '2026-08-17', 'base': 'EUR', 'quote': 'BTN', 'rate': 110.62},
 {'date': '2026-08-18', 'base': 'EUR', 'quote': 'BWP', 'rate': 15.504},
 {'date': '2026-08-18', 'base': 'EUR', 'quote': 'BYN', 'rate': 3.4847},
 {'date': '2026-08-18', 'base': 'EUR', 'quote': 'BZD', 'rate': 2.3608},
 {'date': '2026-08-18', 'base': 'EUR', 'quote': 'CAD', 'rate': 1.6062},
 {'date': '2026-08-17', 'base': 'EUR', 'quote': 'CDF', 'rate': 2628.55},
 {'date': '2026-08-18', 'base': 'EUR', 'quote': 'CHF', 'rate': 0.93813},
 {'date': '2026-08-18', 'base': 'EUR', 'quote': 'CLP', 'rate': 1059.47},
 {'date': '2026-08-18', 'base': 'EUR', 'quote': 'CNH', 'rate': 7.8039},
 {'date': '2026-08-18', 'base': 'EUR', 'quote': 'CNY', 'rate': 7.8037},
 {'date': '2026-08-18', 'base': 'EUR', 'quote': 'COP', 'rate': 3631.43},
 {'date': '2026-08-18', 'base': 'EUR', 'quote': 'CRC', 'rate': 519.83},
 {'date': '2026-08-18', 'base': 'EUR', 'quote': 'CUP', 'rate': 27.802},
 {'date': '2026-08-17', 'base': 'EUR', 'quote': 'CVE', 'rate': 110.21},
 {'date': '2026-08-18', 'base': 'EUR', 'quote': 'CZK', 'rate': 24.188},
 {'date': '2026-08-18', 'base': 'EUR', 'quote': 'DJF', 'rate': 204.88},
 {'date': '2026-08-18', 'base': 'EUR', 'quote': 'DKK', 'rate': 7.4728},
 {'date': '2026-08-18', 'base': 'EUR', 'quote': 'DOP', 'rate': 69.111},
 {'date': '2026-08-18', 'base': 'EUR', 'quote': 'DZD', 'rate': 153.87},
 {'date': '2026-08-18', 'base': 'EUR', 'quote': 'EGP', 'rate': 58.153},
 {'date': '2026-08-17', 'base': 'EUR', 'quote': 'ERN', 'rate': 17.7013},
 {'date': '2026-08-18', 'base': 'EUR', 'quote': 'ETB', 'rate': 186.2},
 {'date': '2026-08-18', 'base': 'EUR', 'quote': 'EUR', 'rate': 1.0},
 {'date': '2026-08-18', 'base': 'EUR', 'quote': 'FJD', 'rate': 2.5683},
 {'date': '2026-08-17', 'base': 'EUR', 'quote': 'FKP', 'rate': 0.8552},
 {'date': '2026-08-18', 'base': 'EUR', 'quote': 'GBP', 'rate': 0.85501},
 {'date': '2026-08-18', 'base': 'EUR', 'quote': 'GEL', 'rate': 3.0233},
 {'date': '2026-08-18', 'base': 'EUR', 'quote': 'GGP', 'rate': 0.85501},
 {'date': '2026-08-18', 'base': 'EUR', 'quote': 'GHS', 'rate': 12.8276},
 {'date': '2026-08-18', 'base': 'EUR', 'quote': 'GIP', 'rate': 0.86555},
 {'date': '2026-08-18', 'base': 'EUR', 'quote': 'GMD', 'rate': 84.31},
 {'date': '2026-08-18', 'base': 'EUR', 'quote': 'GNF', 'rate': 9387},
 {'date': '2026-08-17', 'base': 'EUR', 'quote': 'GTQ', 'rate': 8.8266},
 {'date': '2026-08-18', 'base': 'EUR', 'quote': 'GYD', 'rate': 245.94},
 {'date': '2026-08-18', 'base': 'EUR', 'quote': 'HKD', 'rate': 9.0958},
 {'date': '2026-08-17', 'base': 'EUR', 'quote': 'HNL', 'rate': 31.039},
 {'date': '2026-08-17', 'base': 'EUR', 'quote': 'HTG', 'rate': 151.12},
 {'date': '2026-08-18', 'base': 'EUR', 'quote': 'HUF', 'rate': 362.17},
 {'date': '2026-08-18', 'base': 'EUR', 'quote': 'IDR', 'rate': 20651},
 {'date': '2026-08-18', 'base': 'EUR', 'quote': 'ILS', 'rate': 3.4227},
 {'date': '2026-08-18', 'base': 'EUR', 'quote': 'IMP', 'rate': 0.85501},
 {'date': '2026-08-18', 'base': 'EUR', 'quote': 'INR', 'rate': 110.72},
 {'date': '2026-08-18', 'base': 'EUR', 'quote': 'IQD', 'rate': 1516.28},
 {'date': '2026-08-18', 'base': 'EUR', 'quote': 'IRR', 'rate': 1586523},
 {'date': '2026-08-18', 'base': 'EUR', 'quote': 'ISK', 'rate': 142.12},
 {'date': '2026-08-18', 'base': 'EUR', 'quote': 'JEP', 'rate': 0.85501},
 {'date': '2026-08-18', 'base': 'EUR', 'quote': 'JMD', 'rate': 181.1},
 {'date': '2026-08-18', 'base': 'EUR', 'quote': 'JOD', 'rate': 0.82131},
 {'date': '2026-08-18', 'base': 'EUR', 'quote': 'JPY', 'rate': 184.65},
 {'date': '2026-08-18', 'base': 'EUR', 'quote': 'KES', 'rate': 149.74},
 {'date': '2026-08-18', 'base': 'EUR', 'quote': 'KGS', 'rate': 101.29},
 {'date': '2026-08-18', 'base': 'EUR', 'quote': 'KHR', 'rate': 4695.94},
 {'date': '2026-08-17', 'base': 'EUR', 'quote': 'KMF', 'rate': 491.89},
 {'date': '2026-08-17', 'base': 'EUR', 'quote': 'KPW', 'rate': 150.58},
 {'date': '2026-08-18', 'base': 'EUR', 'quote': 'KRW', 'rate': 1636.17},
 {'date': '2026-08-18', 'base': 'EUR', 'quote': 'KWD', 'rate': 0.3563},
 {'date': '2026-08-18', 'base': 'EUR', 'quote': 'KYD', 'rate': 0.9698},
 {'date': '2026-08-18', 'base': 'EUR', 'quote': 'KZT', 'rate': 534.68},
 {'date': '2026-08-18', 'base': 'EUR', 'quote': 'LAK', 'rate': 25987},
 {'date': '2026-08-18', 'base': 'EUR', 'quote': 'LBP', 'rate': 106017},
 {'date': '2026-08-18', 'base': 'EUR', 'quote': 'LKR', 'rate': 384.64},
 {'date': '2026-08-17', 'base': 'EUR', 'quote': 'LRD', 'rate': 210.34},
 {'date': '2026-08-17', 'base': 'EUR', 'quote': 'LSL', 'rate': 18.727},
 {'date': '2026-08-18', 'base': 'EUR', 'quote': 'LYD', 'rate': 7.3677},
 {'date': '2026-08-18', 'base': 'EUR', 'quote': 'MAD', 'rate': 10.7532},
 {'date': '2026-08-18', 'base': 'EUR', 'quote': 'MDL', 'rate': 19.967},
 {'date': '2026-08-18', 'base': 'EUR', 'quote': 'MGA', 'rate': 4989.22},
 {'date': '2026-08-18', 'base': 'EUR', 'quote': 'MKD', 'rate': 61.604},
 {'date': '2026-08-18', 'base': 'EUR', 'quote': 'MMK', 'rate': 2431.3},
 {'date': '2026-08-18', 'base': 'EUR', 'quote': 'MNT', 'rate': 4164.07},
 {'date': '2026-08-18', 'base': 'EUR', 'quote': 'MOP', 'rate': 9.3687},
 {'date': '2026-08-17', 'base': 'EUR', 'quote': 'MRO', 'rate': 45.838},
 {'date': '2026-08-17', 'base': 'EUR', 'quote': 'MRU', 'rate': 46.438},
 {'date': '2026-08-18', 'base': 'EUR', 'quote': 'MUR', 'rate': 54.499},
 {'date': '2026-08-18', 'base': 'EUR', 'quote': 'MVR', 'rate': 17.8913},
 {'date': '2026-08-18', 'base': 'EUR', 'quote': 'MWK', 'rate': 2012.55},
 {'date': '2026-08-18', 'base': 'EUR', 'quote': 'MXN', 'rate': 19.714},
 {'date': '2026-08-18', 'base': 'EUR', 'quote': 'MYR', 'rate': 4.707},
 {'date': '2026-08-18', 'base': 'EUR', 'quote': 'MZN', 'rate': 73.634},
 {'date': '2026-08-17', 'base': 'EUR', 'quote': 'NAD', 'rate': 18.7338},
 {'date': '2026-08-18', 'base': 'EUR', 'quote': 'NGN', 'rate': 1569.18},
 {'date': '2026-08-18', 'base': 'EUR', 'quote': 'NIO', 'rate': 42.564},
 {'date': '2026-08-18', 'base': 'EUR', 'quote': 'NOK', 'rate': 10.9172},
 {'date': '2026-08-18', 'base': 'EUR', 'quote': 'NPR', 'rate': 177.24},
 {'date': '2026-08-18', 'base': 'EUR', 'quote': 'NZD', 'rate': 1.9614},
 {'date': '2026-08-18', 'base': 'EUR', 'quote': 'OMR', 'rate': 0.44541},
 {'date': '2026-08-17', 'base': 'EUR', 'quote': 'PAB', 'rate': 1.157},
 {'date': '2026-08-18', 'base': 'EUR', 'quote': 'PEN', 'rate': 3.8928},
 {'date': '2026-08-18', 'base': 'EUR', 'quote': 'PGK', 'rate': 5.1141},
 {'date': '2026-08-18', 'base': 'EUR', 'quote': 'PHP', 'rate': 71.281},
 {'date': '2026-08-18', 'base': 'EUR', 'quote': 'PKR', 'rate': 322.57},
 {'date': '2026-08-18', 'base': 'EUR', 'quote': 'PLN', 'rate': 4.3054},
 {'date': '2026-08-18', 'base': 'EUR', 'quote': 'PYG', 'rate': 6967},
 {'date': '2026-08-18', 'base': 'EUR', 'quote': 'QAR', 'rate': 4.2166},
 {'date': '2026-08-18', 'base': 'EUR', 'quote': 'RON', 'rate': 5.2368},
 {'date': '2026-08-18', 'base': 'EUR', 'quote': 'RSD', 'rate': 117.31},
 {'date': '2026-08-18', 'base': 'EUR', 'quote': 'RUB', 'rate': 98.33},
 {'date': '2026-08-18', 'base': 'EUR', 'quote': 'RWF', 'rate': 1703.01},
 {'date': '2026-08-18', 'base': 'EUR', 'quote': 'SAR', 'rate': 4.344},
 {'date': '2026-08-18', 'base': 'EUR', 'quote': 'SBD', 'rate': 9.2946},
 {'date': '2026-08-18', 'base': 'EUR', 'quote': 'SCR', 'rate': 16.8077},
 {'date': '2026-08-18', 'base': 'EUR', 'quote': 'SDG', 'rate': 695.07},
 {'date': '2026-08-18', 'base': 'EUR', 'quote': 'SEK', 'rate': 11.0023},
 {'date': '2026-08-18', 'base': 'EUR', 'quote': 'SGD', 'rate': 1.4795},
 {'date': '2026-08-17', 'base': 'EUR', 'quote': 'SHP', 'rate': 0.8552},
 {'date': '2026-08-17', 'base': 'EUR', 'quote': 'SLE', 'rate': 28.281},
 {'date': '2026-08-17', 'base': 'EUR', 'quote': 'SOS', 'rate': 661.17},
 {'date': '2026-08-17', 'base': 'EUR', 'quote': 'SRD', 'rate': 43.865},
 {'date': '2026-08-17', 'base': 'EUR', 'quote': 'SSP', 'rate': 6303},
 {'date': '2026-08-17', 'base': 'EUR', 'quote': 'STN', 'rate': 24.55},
 {'date': '2026-08-17', 'base': 'EUR', 'quote': 'SVC', 'rate': 10.126},
 {'date': '2026-08-18', 'base': 'EUR', 'quote': 'SYP', 'rate': 141.27},
 {'date': '2026-08-17', 'base': 'EUR', 'quote': 'SZL', 'rate': 18.7188},
 {'date': '2026-08-18', 'base': 'EUR', 'quote': 'THB', 'rate': 38.268},
 {'date': '2026-08-18', 'base': 'EUR', 'quote': 'TJS', 'rate': 10.6994},
 {'date': '2026-08-18', 'base': 'EUR', 'quote': 'TMT', 'rate': 4.0544},
 {'date': '2026-08-18', 'base': 'EUR', 'quote': 'TND', 'rate': 3.3818},
 {'date': '2026-08-17', 'base': 'EUR', 'quote': 'TOP', 'rate': 2.7374},
 {'date': '2026-08-18', 'base': 'EUR', 'quote': 'TRY', 'rate': 55.484},
 {'date': '2026-08-17', 'base': 'EUR', 'quote': 'TTD', 'rate': 7.8001},
 {'date': '2026-08-18', 'base': 'EUR', 'quote': 'TWD', 'rate': 36.914},
 {'date': '2026-08-18', 'base': 'EUR', 'quote': 'TZS', 'rate': 3058.06},
 {'date': '2026-08-18', 'base': 'EUR', 'quote': 'UAH', 'rate': 51.801},
 {'date': '2026-08-18', 'base': 'EUR', 'quote': 'UGX', 'rate': 4308.49},
 {'date': '2026-08-18', 'base': 'EUR', 'quote': 'USD', 'rate': 1.1584},
 {'date': '2026-08-18', 'base': 'EUR', 'quote': 'UYU', 'rate': 46.595},
 {'date': '2026-08-18', 'base': 'EUR', 'quote': 'UZS', 'rate': 13762},
 {'date': '2026-08-18', 'base': 'EUR', 'quote': 'VES', 'rate': 892.15},
 {'date': '2026-08-18', 'base': 'EUR', 'quote': 'VND', 'rate': 30244},
 {'date': '2026-08-18', 'base': 'EUR', 'quote': 'VUV', 'rate': 135.6},
 {'date': '2026-08-18', 'base': 'EUR', 'quote': 'WST', 'rate': 3.1417},
 {'date': '2026-08-17', 'base': 'EUR', 'quote': 'XAF', 'rate': 655.64},
 {'date': '2026-08-18', 'base': 'EUR', 'quote': 'XAG', 'rate': 0.01773},
 {'date': '2026-08-18', 'base': 'EUR', 'quote': 'XAU', 'rate': 0.00026},
 {'date': '2026-08-18', 'base': 'EUR', 'quote': 'XCD', 'rate': 3.1858},
 {'date': '2026-08-17', 'base': 'EUR', 'quote': 'XCG', 'rate': 2.0749},
 {'date': '2026-08-18', 'base': 'EUR', 'quote': 'XDR', 'rate': 0.84675},
 {'date': '2026-08-17', 'base': 'EUR', 'quote': 'XOF', 'rate': 655.64},
 {'date': '2026-08-18', 'base': 'EUR', 'quote': 'XPD', 'rate': 0.00088},
 {'date': '2026-08-17', 'base': 'EUR', 'quote': 'XPF', 'rate': 119.25},
 {'date': '2026-08-18', 'base': 'EUR', 'quote': 'XPT', 'rate': 0.00066},
 {'date': '2026-08-18', 'base': 'EUR', 'quote': 'YER', 'rate': 274.61},
 {'date': '2026-08-18', 'base': 'EUR', 'quote': 'ZAR', 'rate': 18.7323},
 {'date': '2026-08-18', 'base': 'EUR', 'quote': 'ZMW', 'rate': 21.771},
 {'date': '2026-08-17', 'base': 'EUR', 'quote': 'ZWG', 'rate': 30.85}]

Revisando la sección de endpoints, podemos ver los tipos de cambio actuales con el endpoint:

/v2/rates

También podemos cambiar la divisa (currency) base con el endpoint:

/v2/rates?base={currency}

Podemos filtrar tipos de cambio para una fecha concreta con:

/v2/rates?date={YYYY-MM-DD}

Podemos obtener una serie temporal entre dos fechas con:

/v2/rates?from={YYYY-MM-DD}&to={YYYY-MM-DD}

In [10]:
# Hacemos una petición sencilla

response = requests.get(
    url,
    params={
        "base": "EUR",
        "quotes": "USD,GBP"
    }
)

print("Status code:", response.status_code)

data = response.json()

print(data)

Status code: 200
[{'date': '2026-08-18', 'base': 'EUR', 'quote': 'GBP', 'rate': 0.85501}, {'date': '2026-08-18', 'base': 'EUR', 'quote': 'USD', 'rate': 1.1584}]

In [11]:
# Imprimimos algunos de los campos de la respuesta JSON

for currency in data:
    print(
        f"Date: {currency['date']} | "
        f"From: {currency['base']} | "
        f"To: {currency['quote']} | "
        f"Rate of change: {currency['rate']}"
    )

Date: 2026-08-18 | From: EUR | To: GBP | Rate of change: 0.85501
Date: 2026-08-18 | From: EUR | To: USD | Rate of change: 1.1584

In [12]:
# Lo convertimos a DataFrame y lo mostramos
df_rates = pd.DataFrame(data)

df_rates

         date base quote     rate
0  2026-08-18  EUR   GBP  0.85501
1  2026-08-18  EUR   USD  1.15840

################################################################

## Explotación de Open Data Barcelona

El Ayuntamiento de Barcelona dispone de un amplio catálogo de datos abiertos que puede utilizarse para desarrollar análisis sobre diferentes aspectos de la ciudad.

El equipo quiere incorporar una fuente de Open Data a sus procesos de análisis y necesita identificar un conjunto de datos que pueda resultar relevante para un futuro proyecto.

Deberás explorar el catálogo de Open Data BCN, localizar un dataset de interés y comprobar que dispone de información estructurada que pueda ser consumida mediante su API.

Una vez seleccionado el conjunto de datos, realizarás una extracción de información suficiente para trabajar con ella y la transformarás en un DataFrame de pandas.

Finalmente, el conjunto de datos obtenido deberá quedar almacenado en formato CSV para poder reutilizarlo posteriormente en otros procesos de análisis.

### Objetivo de negocio

Completar un pequeño flujo de adquisición y preparación de datos procedentes de una fuente pública real, dejando el dataset preparado para incorporarlo a un futuro proceso de análisis.

El resultado final debe permitir pasar de una fuente externa de datos abiertos a un fichero estructurado y reutilizable:

Open Data BCN → API → datos estructurados → DataFrame → CSV

In [13]:
# Creamos la URL
base_url = "https://opendata-ajuntament.barcelona.cat/data/api/action/"

url = base_url + "package_search"

# Buscamos un dataset con package_search relacionado con la electricidad
params = {
    "q": "electric"
}

response = requests.get(url, params=params)

print(response.status_code)

data = response.json()
data

200

{'help': 'https://opendata-ajuntament.barcelona.cat/data/api/3/action/help_show?name=package_search',
 'success': True,
 'result': {'count': 7,
  'sort': 'fecha_publicacion desc',
  'facets': {},
  'results': [{'notes_translated': {'ca': 'Consum d’electricitat diari per codi postal, sector econòmic i tram horari a la ciutat  de Barcelona, segons les dades proporcionades per la plataforma __[Datadis](https://datadis.es)__.\r\n\r\n\r\n ',
     'en': 'Daily electric cosumption by postal code, economic sector and time interval in the city of Barcelona, according to the data provided by the  __[Datadis](https://datadis.es)__ platform.  \r\n\r\n ',
     'es': 'Consumo eléctrico diario por código postal, sector económico y tramo horario  en la ciudad de Barcelona, según los datos proporcionados por la plataforma __[Datadis](https://datadis.es)__\r\n\r\n  '},
    'geolocation': 'No',
    'dades_alt_valor': 'Estadistica',
    'url_tornada': {'ca': 'https://datadis.es',
     'en': 'https://datadis.es',
     'es': 'https://datadis.es'},
    'dataset_fields_description': "Les dades  s'actualitzen mensualment, amb un decalatge que pot ser de 2 o 3 mesos,  sempre segons la disponibilitat de la plataforma Datadis.",
    'fuente': 'Datadis. La plataforma de dades de consum elèctric',
    'tag': 'Any 2019,Any 2020,Any 2021,Consum elèctric,Electricitat,Codi postal,Any 2022,Any 2023,Any 2024,Any 2025,Alt Valor',
    'private': False,
    'num_tags': 11,
    'code': 'Consum-electricitat-bcn',
    'frequency': 'MENSUAL',
    'id': 'd9479057-781f-42b4-85e6-721bd0284130',
    'title_translated': {'ca': 'Consum d’electricitat (MWh) per codi postal, sector econòmic i tram horari a la ciutat de Barcelona',
     'en': 'Electricity consumption by postal code, economic sector and time interval in teh city of Barcelona',
     'es': 'Consumo de electricidad (MWh) por código postal, sector económico y tramo horario en la ciudad de Barcelona'},
    'metadata_modified': '2026-05-06T09:22:58.744999',
    'author': 'Gerència Municipal',
    'author_email': None,
    'isopen': True,
    'long_format': 'Yes',
    'state': 'active',
    'version': '',
    'mar_od': 'Yes',
    'relationships_as_object': [],
    'department': "Oficina Municipal de Dades - Departament d'Estadística i Difusió de Dades",
    'creator_user_id': '219a3f82-aa64-4df5-ae10-2509ec02d647',
    'type': 'dataset',
    'resources': [{'api_access_number_absolute': '87',
      'cache_last_updated': None,
      'incorporated_in_cityos_res': 'No',
      'token_type': '',
      'package_id': 'd9479057-781f-42b4-85e6-721bd0284130',
      'datastore_active': False,
      'id': '635923fe-9e3b-40d3-857d-aaa9a6913531',
      'description': '',
      'state': 'active',
      'api_access_number': '20',
      'size': '12376371',
      'token_required': 'No',
      'hash': '',
      'token_name': '',
      'format': 'CSV',
      'downloads': '459',
      'mimetype_inner': None,
      'url_type': None,
      'token_provider': '',
      'column_types': '',
      'hide_url': 'No',
      'token_version': '',
      'mimetype': None,
      'cache_url': None,
      'name': '2025_consum_electricitat_BCN.csv',
      'created': '2025-02-26T11:39:16.731271',
      'url': 'https://opendata-ajuntament.barcelona.cat/data/dataset/d9479057-781f-42b4-85e6-721bd0284130/resource/635923fe-9e3b-40d3-857d-aaa9a6913531/download',
      'downloads_absolute': '636',
      'map_visualization_res': 'none',
      'qa': '{\'updated\': \'2026-08-18T02:06:54.284338\', \'openness_score\': 3, \'archival_timestamp\': None, \'format\': u\'CSV\', \'created\': \'2025-02-27T02:05:52.573216\', \'resource_timestamp\': None, \'openness_score_reason\': u\'This file had not been downloaded at the time of scoring it. URL extension "csv" relates to format "CSV" and receives score: 3.\'}',
      'last_modified': None,
      'position': 0,
      'revision_id': 'd4d7c26a-7689-417c-9fec-e1a2e51d4cf4',
      'resource_type': None},
     {'cache_last_updated': None,
      'token_type': '',
      'package_id': 'd9479057-781f-42b4-85e6-721bd0284130',
      'datastore_active': True,
      'id': '6f3a256a-dba6-46ac-88a4-546b93cb46da',
      'size': '13588121',
      'state': 'active',
      'api_access_number': '750',
      'api_access_number_absolute': '4723',
      'token_required': 'No',
      'hash': '',
      'description': '',
      'format': 'CSV',
      'downloads': '523',
      'mimetype_inner': None,
      'url_type': None,
      'token_provider': '',
      'column_types': '',
      'hide_url': 'No',
      'mimetype': None,
      'cache_url': None,
      'name': '2024_consum_electricitat_bcn.csv',
      'created': '2024-04-03T18:07:38.704596',
      'url': 'https://opendata-ajuntament.barcelona.cat/data/dataset/d9479057-781f-42b4-85e6-721bd0284130/resource/6f3a256a-dba6-46ac-88a4-546b93cb46da/download',
      'downloads_absolute': '643',
      'map_visualization_res': 'none',
      'qa': '{\'updated\': \'2026-08-18T02:06:54.310693\', \'openness_score\': 3, \'archival_timestamp\': None, \'format\': u\'CSV\', \'created\': \'2024-04-04T02:05:28.808034\', \'resource_timestamp\': None, \'openness_score_reason\': u\'This file had not been downloaded at the time of scoring it. URL extension "csv" relates to format "CSV" and receives score: 3.\'}',
      'last_modified': None,
      'position': 1,
      'revision_id': 'd4d7c26a-7689-417c-9fec-e1a2e51d4cf4',
      'resource_type': None},
     {'cache_last_updated': None,
      'token_type': '',
      'package_id': 'd9479057-781f-42b4-85e6-721bd0284130',
      'datastore_active': True,
      'id': '25caee3a-a9f2-4e1a-8c8b-1b5fcac4f152',
      'size': '14313373',
      'state': 'active',
      'api_access_number': '1007',
      'api_access_number_absolute': '1259',
      'token_required': 'No',
      'hash': '',
      'description': '',
      'format': 'CSV',
      'downloads': '757',
      'mimetype_inner': None,
      'url_type': '',
      'token_provider': '',
      'column_types': '',
      'hide_url': 'No',
      'mimetype': None,
      'cache_url': None,
      'name': '2023_consum_electricitat_bcn.csv',
      'created': '2023-04-17T08:23:40.327143',
      'url': 'https://opendata-ajuntament.barcelona.cat/data/dataset/d9479057-781f-42b4-85e6-721bd0284130/resource/25caee3a-a9f2-4e1a-8c8b-1b5fcac4f152/download',
      'downloads_absolute': '980',
      'map_visualization_res': 'none',
      'qa': '{\'updated\': \'2026-08-18T02:06:54.323394\', \'openness_score\': 3, \'archival_timestamp\': None, \'format\': u\'CSV\', \'created\': \'2023-04-18T02:04:20.157854\', \'resource_timestamp\': None, \'openness_score_reason\': u\'This file had not been downloaded at the time of scoring it. URL extension "csv" relates to format "CSV" and receives score: 3.\'}',
      'last_modified': '2024-01-09T18:17:18.707567',
      'position': 2,
      'revision_id': 'd4d7c26a-7689-417c-9fec-e1a2e51d4cf4',
      'resource_type': None},
     {'api_access_number_absolute': '1298',
      'cache_last_updated': None,
      'incorporated_in_cityos_res': 'No',
      'token_type': '',
      'package_id': 'd9479057-781f-42b4-85e6-721bd0284130',
      'datastore_active': True,
      'id': 'e685fa1a-9fbe-41a4-98a0-173464cd0c5f',
      'description': '',
      'state': 'active',
      'api_access_number': '1038',
      'size': '14947159',
      'token_required': 'No',
      'hash': '',
      'token_name': '',
      'format': 'CSV',
      'downloads': '705',
      'mimetype_inner': None,
      'url_type': '',
      'token_provider': '',
      'column_types': '[Integer, String, Integer, String, String, Integer]',
      'hide_url': 'No',
      'token_version': '',
      'mimetype': None,
      'cache_url': None,
      'name': '2022_consum_electricitat_bcn.csv',
      'created': '2022-12-21T13:15:22.059889',
      'url': 'https://opendata-ajuntament.barcelona.cat/data/dataset/d9479057-781f-42b4-85e6-721bd0284130/resource/e685fa1a-9fbe-41a4-98a0-173464cd0c5f/download',
      'downloads_absolute': '886',
      'map_visualization_res': 'none',
      'qa': '{\'updated\': \'2026-08-18T02:06:54.333135\', \'openness_score\': 3, \'archival_timestamp\': None, \'format\': u\'CSV\', \'created\': \'2022-12-22T02:06:18.613470\', \'resource_timestamp\': None, \'openness_score_reason\': u\'This file had not been downloaded at the time of scoring it. URL extension "csv" relates to format "CSV" and receives score: 3.\'}',
      'last_modified': '2026-05-06T11:22:58.696548',
      'position': 3,
      'revision_id': 'd4d7c26a-7689-417c-9fec-e1a2e51d4cf4',
      'resource_type': None},
     {'cache_last_updated': None,
      'token_type': '',
      'package_id': 'd9479057-781f-42b4-85e6-721bd0284130',
      'datastore_active': True,
      'id': '2b6ef2c2-cbd0-437c-a229-889e992e1dd6',
      'size': '14484539',
      'state': 'active',
      'api_access_number': '21',
      'api_access_number_absolute': '37',
      'token_required': 'No',
      'hash': '',
      'description': '',
      'format': 'CSV',
      'downloads': '733',
      'mimetype_inner': None,
      'url_type': '',
      'token_provider': '',
      'column_types': '',
      'hide_url': 'No',
      'mimetype': None,
      'cache_url': None,
      'name': '2021_consum_electricitat_bcn.csv',
      'created': '2022-12-19T08:31:19.568909',
      'url': 'https://opendata-ajuntament.barcelona.cat/data/dataset/d9479057-781f-42b4-85e6-721bd0284130/resource/2b6ef2c2-cbd0-437c-a229-889e992e1dd6/download',
      'downloads_absolute': '856',
      'map_visualization_res': 'none',
      'qa': '{\'updated\': \'2026-08-18T02:06:54.347605\', \'openness_score\': 3, \'archival_timestamp\': None, \'format\': u\'CSV\', \'created\': \'2022-12-20T02:06:19.766891\', \'resource_timestamp\': None, \'openness_score_reason\': u\'This file had not been downloaded at the time of scoring it. URL extension "csv" relates to format "CSV" and receives score: 3.\'}',
      'last_modified': '2023-12-14T12:59:54.783760',
      'position': 4,
      'revision_id': 'd4d7c26a-7689-417c-9fec-e1a2e51d4cf4',
      'resource_type': None},
     {'cache_last_updated': None,
      'token_type': '',
      'package_id': 'd9479057-781f-42b4-85e6-721bd0284130',
      'datastore_active': True,
      'id': '3c45a329-0414-4055-8f17-82456fc78dea',
      'size': '14574966',
      'state': 'active',
      'api_access_number': '12',
      'api_access_number_absolute': '22',
      'token_required': 'No',
      'hash': '',
      'description': '',
      'format': 'CSV',
      'downloads': '701',
      'mimetype_inner': None,
      'url_type': '',
      'token_provider': '',
      'column_types': '',
      'hide_url': 'No',
      'mimetype': None,
      'cache_url': None,
      'name': '2020_consum_electricitat_bcn.csv',
      'created': '2022-12-19T08:09:47.368630',
      'url': 'https://opendata-ajuntament.barcelona.cat/data/dataset/d9479057-781f-42b4-85e6-721bd0284130/resource/3c45a329-0414-4055-8f17-82456fc78dea/download',
      'downloads_absolute': '794',
      'map_visualization_res': 'none',
      'qa': '{\'updated\': \'2026-08-18T02:06:54.357909\', \'openness_score\': 3, \'archival_timestamp\': None, \'format\': u\'CSV\', \'created\': \'2022-12-20T02:06:19.750493\', \'resource_timestamp\': None, \'openness_score_reason\': u\'This file had not been downloaded at the time of scoring it. URL extension "csv" relates to format "CSV" and receives score: 3.\'}',
      'last_modified': '2023-12-14T12:58:48.376175',
      'position': 5,
      'revision_id': 'd4d7c26a-7689-417c-9fec-e1a2e51d4cf4',
      'resource_type': None},
     {'cache_last_updated': None,
      'token_type': '',
      'package_id': 'd9479057-781f-42b4-85e6-721bd0284130',
      'datastore_active': True,
      'id': '41b9a3e0-f079-4a4a-a8c3-670adc6bfb95',
      'size': '14590134',
      'state': 'active',
      'api_access_number': '12',
      'api_access_number_absolute': '22',
      'token_required': 'No',
      'hash': '',
      'description': '',
      'format': 'CSV',
      'downloads': '623',
      'mimetype_inner': None,
      'url_type': '',
      'token_provider': '',
      'column_types': '',
      'hide_url': 'No',
      'mimetype': None,
      'cache_url': None,
      'name': '2019_consum_electricitat_bcn.csv',
      'created': '2022-12-19T08:08:58.183306',
      'url': 'https://opendata-ajuntament.barcelona.cat/data/dataset/d9479057-781f-42b4-85e6-721bd0284130/resource/41b9a3e0-f079-4a4a-a8c3-670adc6bfb95/download',
      'downloads_absolute': '748',
      'map_visualization_res': 'none',
      'qa': '{\'updated\': \'2026-08-18T02:06:54.382929\', \'openness_score\': 3, \'archival_timestamp\': None, \'format\': u\'CSV\', \'created\': \'2022-12-20T02:06:19.729841\', \'resource_timestamp\': None, \'openness_score_reason\': u\'This file had not been downloaded at the time of scoring it. URL extension "csv" relates to format "CSV" and receives score: 3.\'}',
      'last_modified': '2024-02-06T17:33:57.021759',
      'position': 6,
      'revision_id': 'd4d7c26a-7689-417c-9fec-e1a2e51d4cf4',
      'resource_type': None}],
    'token_required': 'No',
    'decalatgeNum': '2',
    'tags': [{'vocabulary_id': None,
      'state': 'active',
      'display_name': 'Alt Valor',
      'id': 'ebe20eba-8f65-40a9-9c25-4e7ab62b8f45',
      'name': 'Alt Valor'},
     {'vocabulary_id': None,
      'state': 'active',
      'display_name': 'Any 2019',
      'id': '4fdbddac-00a9-480e-a846-8148522b3500',
      'name': 'Any 2019'},
     {'vocabulary_id': None,
      'state': 'active',
      'display_name': 'Any 2020',
      'id': '2ff883a0-d01a-4af3-8235-8407a6e411a7',
      'name': 'Any 2020'},
     {'vocabulary_id': None,
      'state': 'active',
      'display_name': 'Any 2021',
      'id': '28ab7cce-e938-4cca-adc6-800b03070775',
      'name': 'Any 2021'},
     {'vocabulary_id': None,
      'state': 'active',
      'display_name': 'Any 2022',
      'id': '224016e4-81b8-4e60-819b-e7119ced7589',
      'name': 'Any 2022'},
     {'vocabulary_id': None,
      'state': 'active',
      'display_name': 'Any 2023',
      'id': '3f5176c6-4773-426d-b3f4-729d7d47f59d',
      'name': 'Any 2023'},
     {'vocabulary_id': None,
      'state': 'active',
      'display_name': 'Any 2024',
      'id': '283fc2f8-cbae-4ef0-9884-edf991193b9f',
      'name': 'Any 2024'},
     {'vocabulary_id': None,
      'state': 'active',
      'display_name': 'Any 2025',
      'id': '0510e622-4b6e-4f59-994f-41c01b0a8b1f',
      'name': 'Any 2025'},
     {'vocabulary_id': None,
      'state': 'active',
      'display_name': 'Codi postal',
      'id': 'd9451c22-e311-47e2-8a05-fed590dd0ba4',
      'name': 'Codi postal'},
     {'vocabulary_id': None,
      'state': 'active',
      'display_name': 'Consum elèctric',
      'id': '079d8668-3f9a-4024-bc14-b6f76ed2ecab',
      'name': 'Consum elèctric'},
     {'vocabulary_id': None,
      'state': 'active',
      'display_name': 'Electricitat',
      'id': '1eb5411c-f97c-4759-820e-347f54a3835c',
      'name': 'Electricitat'}],
    'ODS_Principal_agenda_2030': 'ODS 7: Energia neta i assequible',
    'fecha_publicacion': '2022-12-20',
    'ODS_Colateral2_agenda_2030': 'N/A',
    'ODS_Colateral1_agenda_2030': 'N/A',
    'license_id': 'CC-BY-4.0',
    'hide_url': 'No',
    'relationships_as_subject': [],
    'license_title': 'Creative Commons Attribution 4.0',
    'groups': [],
    'num_resources': 7,
    'organization': {'code': 'urbanisme-i-infraestructures',
     'display_name': 'Urbanisme i infraestructures',
     'description': 'Town planning and Infrastructures',
     'parent': {'code': 'territori',
      'display_name': 'Territori',
      'description': 'Territory',
      'created': '2017-01-24T16:55:06.680852',
      'package_count': 0,
      'image_display_url': 'https://opendata-ajuntament.barcelona.cat/data/uploads/group/bcn-icon2-territori',
      'description_translated': {'ca': 'Territori',
       'en': 'Territory',
       'es': 'Territorio'},
      'name': 'territori',
      'is_organization': True,
      'state': 'active',
      'image_url': 'bcn-icon2-territori',
      'groups': [],
      'type': 'organization',
      'title': 'Territory',
      'revision_id': '948d611b-5bfd-4878-a817-3bbdd28bae22',
      'title_translated': {'ca': 'Territori',
       'en': 'Territory',
       'es': 'Territorio'},
      'num_followers': 0,
      'id': 'fdb223be-3adc-4145-be97-980bcfbdaa3b',
      'approval_status': 'approved'},
     'created': '2017-01-24T16:55:07.057488',
     'package_count': 67,
     'image_display_url': 'https://opendata-ajuntament.barcelona.cat/data/uploads/group/bcn-icon-urbanisme',
     'tematica_nti': 'urbanismo-infraestructuras',
     'description_translated': {'ca': 'Urbanisme i infraestructures',
      'en': 'Town planning and Infrastructures',
      'es': 'Urbanismo e infraestructuras'},
     'name': 'urbanisme-i-infraestructures',
     'is_organization': True,
     'state': 'active',
     'image_url': 'bcn-icon-urbanisme',
     'groups': [{'capacity': 'public', 'name': 'territori'}],
     'type': 'organization',
     'title': 'Town planning and Infrastructures',
     'revision_id': 'da18f861-8b29-45f5-88eb-ca5449896b24',
     'title_translated': {'ca': 'Urbanisme i infraestructures',
      'en': 'Town planning and Infrastructures',
      'es': 'Urbanismo e infraestructuras'},
     'num_followers': 0,
     'id': '9bf18787-464c-4355-b19e-697055626c77',
     'approval_status': 'approved'},
    'name': 'consum-electricitat-bcn',
    'url': None,
    'notes': 'Daily electric cosumption by postal code, economic sector and time interval in the city of Barcelona, according to the data provided by the  __[Datadis](https://datadis.es)__ platform.  \r\n\r\n ',
    'owner_org': '9bf18787-464c-4355-b19e-697055626c77',
    'load_type': 'link_intern_desde_font_interna',
    'api': 'Yes',
    'license_url': 'https://creativecommons.org/licenses/by/4.0/',
    'historical': 'Yes',
    'title': 'Electricity consumption by postal code, economic sector and time interval in teh city of Barcelona',
    'revision_id': 'aa616106-f494-49c2-ad99-44818a3e42d7',
    'extras': [{'key': '01.Any', 'value': 'Any de les dades'},
     {'key': '02.Data', 'value': 'Data en format YYYY - MM – DD'},
     {'key': '03.Codi_Postal', 'value': ' Codi postal'},
     {'key': '04.Sector_Economic', 'value': 'Sector econòmic'},
     {'key': '05.Tram_Horari', 'value': ' Tram horari en format HH:MM:SS'},
     {'key': '06.Valor', 'value': 'Consum elèctric en megawatt  hores '}]},
   {'notes_translated': {'ca': 'Estat dels ports dels punts de recàrrega del vehicle elèctric de la ciutat de Barcelona',
     'en': 'Status of the ports of the electric vehicle charging points in the city of Barcelona ',
     'es': 'Estado de los puertos de los puntos de recarga del vehículo eléctrico de la ciudad de Barcelona '},
    'geolocation': 'No',
    'dades_alt_valor': 'Mobilitat',
    'url_tornada': {'ca': 'https://www.endolla.barcelona/ca/',
     'en': 'https://www.endolla.barcelona/en/',
     'es': 'https://www.endolla.barcelona/es/'},
    'dataset_fields_description': "__NOTA:Durant els mes de juliol i  fins al 3 d'agost de 2023, i amb la finalitat d'oferir un millor servei, s'ha realitzat un canvi en el software de gestió dels punts de recàrrega del vehicle elèctric  de la ciutat de Barcelona gestionats per B:SM.  \r\nAmb data 3 d'agost de 2023  s'el.limina el recurs estat_ports_realtime.json,  quedant susbtituït per el recurs estat_ports_realtime.json _mi.json.  Perdoneu les molèsties que us puguem ocasionar. __        \r\n\r\n\r\nAquest dataset s'enllaça  mitjançant  __locations__ amb tots els datasets referents a__ [ Recàrrega de vehicle elèctric a la ciutat de Barcelona]( https://opendata-ajuntament.barcelona.cat/data/ca/dataset?q=rec%C3%A0rrega+vehicle+el%C3%A8ctric&sort=fecha_publicacion+desc&tags=Punts+rec%C3%A0rrega+vehicle+el%C3%A8ctric&agrupacio=BSM)__",
    'fuente': 'B:SM Barcelona de Serveis Municipals',

In [14]:
for dataset in data["result"]["results"]:
    print(dataset["name"])
    print(dataset["title"])
    print()

consum-electricitat-bcn
Electricity consumption by postal code, economic sector and time interval in teh city of Barcelona

estat-ports-recarrega-electric
Status of the ports of the electric vehicle charging points in the city of Barcelona

informacio-punts-recarrega-electric
Extended information on electric vehicle charging stations in the city of Barcelona

autenticacions-punts-recarrega-electric
Authentication of electric vehicle charging points in the city of Barcelona

punts-recarrega-vehicles-electrics
Electric vehicle charging stations in the city of Barcelona

bicing
Bicing stations, mechanical and electrical, in the city of Barcelona from August 2018 to March 2019

equipament-companyies-de-serveis
List of services companies in the city of Barcelona

In [15]:
# Nos quedamos con el primer dataset
dataset_name = data["result"]["results"][0]["name"]

url = base_url + "package_show"

params = {
    "id": dataset_name
}

response = requests.get(url, params=params)

dataset = response.json()
dataset["result"]

{'notes_translated': {'ca': 'Consum d’electricitat diari per codi postal, sector econòmic i tram horari a la ciutat  de Barcelona, segons les dades proporcionades per la plataforma __[Datadis](https://datadis.es)__.\r\n\r\n\r\n ',
  'en': 'Daily electric cosumption by postal code, economic sector and time interval in the city of Barcelona, according to the data provided by the  __[Datadis](https://datadis.es)__ platform.  \r\n\r\n ',
  'es': 'Consumo eléctrico diario por código postal, sector económico y tramo horario  en la ciudad de Barcelona, según los datos proporcionados por la plataforma __[Datadis](https://datadis.es)__\r\n\r\n  '},
 'geolocation': 'No',
 'dades_alt_valor': 'Estadistica',
 'url_tornada': {'ca': 'https://datadis.es',
  'en': 'https://datadis.es',
  'es': 'https://datadis.es'},
 'dataset_fields_description': "Les dades  s'actualitzen mensualment, amb un decalatge que pot ser de 2 o 3 mesos,  sempre segons la disponibilitat de la plataforma Datadis.",
 'fuente': 'Datadis. La plataforma de dades de consum elèctric',
 'tag': 'Any 2019,Any 2020,Any 2021,Consum elèctric,Electricitat,Codi postal,Any 2022,Any 2023,Any 2024,Any 2025,Alt Valor',
 'private': False,
 'num_tags': 11,
 'code': 'Consum-electricitat-bcn',
 'frequency': 'MENSUAL',
 'id': 'd9479057-781f-42b4-85e6-721bd0284130',
 'title_translated': {'ca': 'Consum d’electricitat (MWh) per codi postal, sector econòmic i tram horari a la ciutat de Barcelona',
  'en': 'Electricity consumption by postal code, economic sector and time interval in teh city of Barcelona',
  'es': 'Consumo de electricidad (MWh) por código postal, sector económico y tramo horario en la ciudad de Barcelona'},
 'metadata_modified': '2026-05-06T09:22:58.744999',
 'author': 'Gerència Municipal',
 'author_email': None,
 'isopen': True,
 'long_format': 'Yes',
 'state': 'active',
 'version': '',
 'mar_od': 'Yes',
 'relationships_as_object': [],
 'department': "Oficina Municipal de Dades - Departament d'Estadística i Difusió de Dades",
 'creator_user_id': '219a3f82-aa64-4df5-ae10-2509ec02d647',
 'type': 'dataset',
 'resources': [{'api_access_number_absolute': 87,
   'cache_last_updated': None,
   'incorporated_in_cityos_res': 'No',
   'token_type': '',
   'package_id': 'd9479057-781f-42b4-85e6-721bd0284130',
   'datastore_active': False,
   'id': '635923fe-9e3b-40d3-857d-aaa9a6913531',
   'description': '',
   'state': 'active',
   'api_access_number': 20,
   'size': '12376371',
   'token_required': 'No',
   'hash': '',
   'token_name': '',
   'format': 'CSV',
   'downloads': 459,
   'mimetype_inner': None,
   'url_type': None,
   'token_provider': '',
   'column_types': '',
   'hide_url': 'No',
   'token_version': '',
   'mimetype': None,
   'cache_url': None,
   'name': '2025_consum_electricitat_BCN.csv',
   'created': '2025-02-26T11:39:16.731271',
   'url': 'https://opendata-ajuntament.barcelona.cat/data/dataset/d9479057-781f-42b4-85e6-721bd0284130/resource/635923fe-9e3b-40d3-857d-aaa9a6913531/download',
   'downloads_absolute': 636,
   'map_visualization_res': 'none',
   'qa': {'updated': '2026-08-18T02:06:54.284338',
    'openness_score': 3,
    'archival_timestamp': None,
    'format': 'CSV',
    'created': '2025-02-27T02:05:52.573216',
    'resource_timestamp': None,
    'openness_score_reason': 'This file had not been downloaded at the time of scoring it. URL extension "csv" relates to format "CSV" and receives score: 3.'},
   'last_modified': None,
   'position': 0,
   'revision_id': 'd4d7c26a-7689-417c-9fec-e1a2e51d4cf4',
   'resource_type': None},
  {'cache_last_updated': None,
   'token_type': '',
   'package_id': 'd9479057-781f-42b4-85e6-721bd0284130',
   'datastore_active': True,
   'id': '6f3a256a-dba6-46ac-88a4-546b93cb46da',
   'size': '13588121',
   'state': 'active',
   'api_access_number': 750,
   'api_access_number_absolute': 4723,
   'token_required': 'No',
   'hash': '',
   'description': '',
   'format': 'CSV',
   'downloads': 523,
   'mimetype_inner': None,
   'url_type': None,
   'token_provider': '',
   'column_types': '',
   'hide_url': 'No',
   'mimetype': None,
   'cache_url': None,
   'name': '2024_consum_electricitat_bcn.csv',
   'created': '2024-04-03T18:07:38.704596',
   'url': 'https://opendata-ajuntament.barcelona.cat/data/dataset/d9479057-781f-42b4-85e6-721bd0284130/resource/6f3a256a-dba6-46ac-88a4-546b93cb46da/download',
   'downloads_absolute': 643,
   'map_visualization_res': 'none',
   'qa': {'updated': '2026-08-18T02:06:54.310693',
    'openness_score': 3,
    'archival_timestamp': None,
    'format': 'CSV',
    'created': '2024-04-04T02:05:28.808034',
    'resource_timestamp': None,
    'openness_score_reason': 'This file had not been downloaded at the time of scoring it. URL extension "csv" relates to format "CSV" and receives score: 3.'},
   'last_modified': None,
   'position': 1,
   'revision_id': 'd4d7c26a-7689-417c-9fec-e1a2e51d4cf4',
   'resource_type': None},
  {'cache_last_updated': None,
   'token_type': '',
   'package_id': 'd9479057-781f-42b4-85e6-721bd0284130',
   'datastore_active': True,
   'id': '25caee3a-a9f2-4e1a-8c8b-1b5fcac4f152',
   'size': '14313373',
   'state': 'active',
   'api_access_number': 1007,
   'api_access_number_absolute': 1259,
   'token_required': 'No',
   'hash': '',
   'description': '',
   'format': 'CSV',
   'downloads': 757,
   'mimetype_inner': None,
   'url_type': '',
   'token_provider': '',
   'column_types': '',
   'hide_url': 'No',
   'mimetype': None,
   'cache_url': None,
   'name': '2023_consum_electricitat_bcn.csv',
   'created': '2023-04-17T08:23:40.327143',
   'url': 'https://opendata-ajuntament.barcelona.cat/data/dataset/d9479057-781f-42b4-85e6-721bd0284130/resource/25caee3a-a9f2-4e1a-8c8b-1b5fcac4f152/download',
   'downloads_absolute': 980,
   'map_visualization_res': 'none',
   'qa': {'updated': '2026-08-18T02:06:54.323394',
    'openness_score': 3,
    'archival_timestamp': None,
    'format': 'CSV',
    'created': '2023-04-18T02:04:20.157854',
    'resource_timestamp': None,
    'openness_score_reason': 'This file had not been downloaded at the time of scoring it. URL extension "csv" relates to format "CSV" and receives score: 3.'},
   'last_modified': '2024-01-09T18:17:18.707567',
   'position': 2,
   'revision_id': 'd4d7c26a-7689-417c-9fec-e1a2e51d4cf4',
   'resource_type': None},
  {'api_access_number_absolute': 1298,
   'cache_last_updated': None,
   'incorporated_in_cityos_res': 'No',
   'token_type': '',
   'package_id': 'd9479057-781f-42b4-85e6-721bd0284130',
   'datastore_active': True,
   'id': 'e685fa1a-9fbe-41a4-98a0-173464cd0c5f',
   'description': '',
   'state': 'active',
   'api_access_number': 1038,
   'size': '14947159',
   'token_required': 'No',
   'hash': '',
   'token_name': '',
   'format': 'CSV',
   'downloads': 705,
   'mimetype_inner': None,
   'url_type': '',
   'token_provider': '',
   'column_types': '[Integer, String, Integer, String, String, Integer]',
   'hide_url': 'No',
   'token_version': '',
   'mimetype': None,
   'cache_url': None,
   'name': '2022_consum_electricitat_bcn.csv',
   'created': '2022-12-21T13:15:22.059889',
   'url': 'https://opendata-ajuntament.barcelona.cat/data/dataset/d9479057-781f-42b4-85e6-721bd0284130/resource/e685fa1a-9fbe-41a4-98a0-173464cd0c5f/download',
   'downloads_absolute': 886,
   'map_visualization_res': 'none',
   'qa': {'updated': '2026-08-18T02:06:54.333135',
    'openness_score': 3,
    'archival_timestamp': None,
    'format': 'CSV',
    'created': '2022-12-22T02:06:18.613470',
    'resource_timestamp': None,
    'openness_score_reason': 'This file had not been downloaded at the time of scoring it. URL extension "csv" relates to format "CSV" and receives score: 3.'},
   'last_modified': '2026-05-06T11:22:58.696548',
   'position': 3,
   'revision_id': 'd4d7c26a-7689-417c-9fec-e1a2e51d4cf4',
   'resource_type': None},
  {'cache_last_updated': None,
   'token_type': '',
   'package_id': 'd9479057-781f-42b4-85e6-721bd0284130',
   'datastore_active': True,
   'id': '2b6ef2c2-cbd0-437c-a229-889e992e1dd6',
   'size': '14484539',
   'state': 'active',
   'api_access_number': 21,
   'api_access_number_absolute': 37,
   'token_required': 'No',
   'hash': '',
   'description': '',
   'format': 'CSV',
   'downloads': 733,
   'mimetype_inner': None,
   'url_type': '',
   'token_provider': '',
   'column_types': '',
   'hide_url': 'No',
   'mimetype': None,
   'cache_url': None,
   'name': '2021_consum_electricitat_bcn.csv',
   'created': '2022-12-19T08:31:19.568909',
   'url': 'https://opendata-ajuntament.barcelona.cat/data/dataset/d9479057-781f-42b4-85e6-721bd0284130/resource/2b6ef2c2-cbd0-437c-a229-889e992e1dd6/download',
   'downloads_absolute': 856,
   'map_visualization_res': 'none',
   'qa': {'updated': '2026-08-18T02:06:54.347605',
    'openness_score': 3,
    'archival_timestamp': None,
    'format': 'CSV',
    'created': '2022-12-20T02:06:19.766891',
    'resource_timestamp': None,
    'openness_score_reason': 'This file had not been downloaded at the time of scoring it. URL extension "csv" relates to format "CSV" and receives score: 3.'},
   'last_modified': '2023-12-14T12:59:54.783760',
   'position': 4,
   'revision_id': 'd4d7c26a-7689-417c-9fec-e1a2e51d4cf4',
   'resource_type': None},
  {'cache_last_updated': None,
   'token_type': '',
   'package_id': 'd9479057-781f-42b4-85e6-721bd0284130',
   'datastore_active': True,
   'id': '3c45a329-0414-4055-8f17-82456fc78dea',
   'size': '14574966',
   'state': 'active',
   'api_access_number': 12,
   'api_access_number_absolute': 22,
   'token_required': 'No',
   'hash': '',
   'description': '',
   'format': 'CSV',
   'downloads': 701,
   'mimetype_inner': None,
   'url_type': '',
   'token_provider': '',
   'column_types': '',
   'hide_url': 'No',
   'mimetype': None,
   'cache_url': None,
   'name': '2020_consum_electricitat_bcn.csv',
   'created': '2022-12-19T08:09:47.368630',
   'url': 'https://opendata-ajuntament.barcelona.cat/data/dataset/d9479057-781f-42b4-85e6-721bd0284130/resource/3c45a329-0414-4055-8f17-82456fc78dea/download',
   'downloads_absolute': 794,
   'map_visualization_res': 'none',
   'qa': {'updated': '2026-08-18T02:06:54.357909',
    'openness_score': 3,
    'archival_timestamp': None,
    'format': 'CSV',
    'created': '2022-12-20T02:06:19.750493',
    'resource_timestamp': None,
    'openness_score_reason': 'This file had not been downloaded at the time of scoring it. URL extension "csv" relates to format "CSV" and receives score: 3.'},
   'last_modified': '2023-12-14T12:58:48.376175',
   'position': 5,
   'revision_id': 'd4d7c26a-7689-417c-9fec-e1a2e51d4cf4',
   'resource_type': None},
  {'cache_last_updated': None,
   'token_type': '',
   'package_id': 'd9479057-781f-42b4-85e6-721bd0284130',
   'datastore_active': True,
   'id': '41b9a3e0-f079-4a4a-a8c3-670adc6bfb95',
   'size': '14590134',
   'state': 'active',
   'api_access_number': 12,
   'api_access_number_absolute': 22,
   'token_required': 'No',
   'hash': '',
   'description': '',
   'format': 'CSV',
   'downloads': 623,
   'mimetype_inner': None,
   'url_type': '',
   'token_provider': '',
   'column_types': '',
   'hide_url': 'No',
   'mimetype': None,
   'cache_url': None,
   'name': '2019_consum_electricitat_bcn.csv',
   'created': '2022-12-19T08:08:58.183306',
   'url': 'https://opendata-ajuntament.barcelona.cat/data/dataset/d9479057-781f-42b4-85e6-721bd0284130/resource/41b9a3e0-f079-4a4a-a8c3-670adc6bfb95/download',
   'downloads_absolute': 748,
   'map_visualization_res': 'none',
   'qa': {'updated': '2026-08-18T02:06:54.382929',
    'openness_score': 3,
    'archival_timestamp': None,
    'format': 'CSV',
    'created': '2022-12-20T02:06:19.729841',
    'resource_timestamp': None,
    'openness_score_reason': 'This file had not been downloaded at the time of scoring it. URL extension "csv" relates to format "CSV" and receives score: 3.'},
   'last_modified': '2024-02-06T17:33:57.021759',
   'position': 6,
   'revision_id': 'd4d7c26a-7689-417c-9fec-e1a2e51d4cf4',
   'resource_type': None}],
 'token_required': 'No',
 'decalatgeNum': '2',
 'tags': [{'vocabulary_id': None,
   'state': 'active',
   'display_name': 'Alt Valor',
   'id': 'ebe20eba-8f65-40a9-9c25-4e7ab62b8f45',
   'name': 'Alt Valor'},
  {'vocabulary_id': None,
   'state': 'active',
   'display_name': 'Any 2019',
   'id': '4fdbddac-00a9-480e-a846-8148522b3500',
   'name': 'Any 2019'},
  {'vocabulary_id': None,
   'state': 'active',
   'display_name': 'Any 2020',
   'id': '2ff883a0-d01a-4af3-8235-8407a6e411a7',
   'name': 'Any 2020'},
  {'vocabulary_id': None,
   'state': 'active',
   'display_name': 'Any 2021',
   'id': '28ab7cce-e938-4cca-adc6-800b03070775',
   'name': 'Any 2021'},
  {'vocabulary_id': None,
   'state': 'active',
   'display_name': 'Any 2022',
   'id': '224016e4-81b8-4e60-819b-e7119ced7589',
   'name': 'Any 2022'},
  {'vocabulary_id': None,
   'state': 'active',
   'display_name': 'Any 2023',
   'id': '3f5176c6-4773-426d-b3f4-729d7d47f59d',
   'name': 'Any 2023'},
  {'vocabulary_id': None,
   'state': 'active',
   'display_name': 'Any 2024',
   'id': '283fc2f8-cbae-4ef0-9884-edf991193b9f',
   'name': 'Any 2024'},
  {'vocabulary_id': None,
   'state': 'active',
   'display_name': 'Any 2025',
   'id': '0510e622-4b6e-4f59-994f-41c01b0a8b1f',
   'name': 'Any 2025'},
  {'vocabulary_id': None,
   'state': 'active',
   'display_name': 'Codi postal',
   'id': 'd9451c22-e311-47e2-8a05-fed590dd0ba4',
   'name': 'Codi postal'},
  {'vocabulary_id': None,
   'state': 'active',
   'display_name': 'Consum elèctric',
   'id': '079d8668-3f9a-4024-bc14-b6f76ed2ecab',
   'name': 'Consum elèctric'},
  {'vocabulary_id': None,
   'state': 'active',
   'display_name': 'Electricitat',
   'id': '1eb5411c-f97c-4759-820e-347f54a3835c',
   'name': 'Electricitat'}],
 'ODS_Principal_agenda_2030': 'ODS 7: Energia neta i assequible',
 'fecha_publicacion': '2022-12-20',
 'ODS_Colateral2_agenda_2030': 'N/A',
 'ODS_Colateral1_agenda_2030': 'N/A',
 'license_id': 'CC-BY-4.0',
 'hide_url': 'No',
 'relationships_as_subject': [],
 'license_title': 'Creative Commons Attribution 4.0',
 'groups': [],
 'num_resources': 7,
 'organization': {'description': '',
  'created': '2017-01-24T16:55:07.057488',
  'title': 'Urbanisme i infraestructures',
  'name': 'urbanisme-i-infraestructures',
  'is_organization': True,
  'state': 'active',
  'image_url': 'bcn-icon-urbanisme',
  'revision_id': 'da18f861-8b29-45f5-88eb-ca5449896b24',
  'type': 'organization',
  'id': '9bf18787-464c-4355-b19e-697055626c77',
  'approval_status': 'approved'},
 'name': 'consum-electricitat-bcn',
 'url': None,
 'notes': 'Daily electric cosumption by postal code, economic sector and time interval in the city of Barcelona, according to the data provided by the  __[Datadis](https://datadis.es)__ platform.  \r\n\r\n ',
 'owner_org': '9bf18787-464c-4355-b19e-697055626c77',
 'load_type': 'link_intern_desde_font_interna',
 'qa': {'openness_score_reason': 'This file had not been downloaded at the time of scoring it. URL extension "csv" relates to format "CSV" and receives score: 3.',
  'updated': '2026-08-18T02:06:54.382929',
  'openness_score': 3},
 'api': 'Yes',
 'license_url': 'https://creativecommons.org/licenses/by/4.0/',
 'historical': 'Yes',
 'title': 'Electricity consumption by postal code, economic sector and time interval in teh city of Barcelona',
 'revision_id': 'aa616106-f494-49c2-ad99-44818a3e42d7',
 'extras': [{'key': '01.Any', 'value': 'Any de les dades'},
  {'key': '02.Data', 'value': 'Data en format YYYY - MM – DD'},
  {'key': '03.Codi_Postal', 'value': ' Codi postal'},
  {'key': '04.Sector_Economic', 'value': 'Sector econòmic'},
  {'key': '05.Tram_Horari', 'value': ' Tram horari en format HH:MM:SS'},
  {'key': '06.Valor', 'value': 'Consum elèctric en megawatt  hores '}]}

In [16]:
# Buscamos los recursos diponibles
dataset["result"]["resources"]

[{'api_access_number_absolute': 87,
  'cache_last_updated': None,
  'incorporated_in_cityos_res': 'No',
  'token_type': '',
  'package_id': 'd9479057-781f-42b4-85e6-721bd0284130',
  'datastore_active': False,
  'id': '635923fe-9e3b-40d3-857d-aaa9a6913531',
  'description': '',
  'state': 'active',
  'api_access_number': 20,
  'size': '12376371',
  'token_required': 'No',
  'hash': '',
  'token_name': '',
  'format': 'CSV',
  'downloads': 459,
  'mimetype_inner': None,
  'url_type': None,
  'token_provider': '',
  'column_types': '',
  'hide_url': 'No',
  'token_version': '',
  'mimetype': None,
  'cache_url': None,
  'name': '2025_consum_electricitat_BCN.csv',
  'created': '2025-02-26T11:39:16.731271',
  'url': 'https://opendata-ajuntament.barcelona.cat/data/dataset/d9479057-781f-42b4-85e6-721bd0284130/resource/635923fe-9e3b-40d3-857d-aaa9a6913531/download',
  'downloads_absolute': 636,
  'map_visualization_res': 'none',
  'qa': {'updated': '2026-08-18T02:06:54.284338',
   'openness_score': 3,
   'archival_timestamp': None,
   'format': 'CSV',
   'created': '2025-02-27T02:05:52.573216',
   'resource_timestamp': None,
   'openness_score_reason': 'This file had not been downloaded at the time of scoring it. URL extension "csv" relates to format "CSV" and receives score: 3.'},
  'last_modified': None,
  'position': 0,
  'revision_id': 'd4d7c26a-7689-417c-9fec-e1a2e51d4cf4',
  'resource_type': None},
 {'cache_last_updated': None,
  'token_type': '',
  'package_id': 'd9479057-781f-42b4-85e6-721bd0284130',
  'datastore_active': True,
  'id': '6f3a256a-dba6-46ac-88a4-546b93cb46da',
  'size': '13588121',
  'state': 'active',
  'api_access_number': 750,
  'api_access_number_absolute': 4723,
  'token_required': 'No',
  'hash': '',
  'description': '',
  'format': 'CSV',
  'downloads': 523,
  'mimetype_inner': None,
  'url_type': None,
  'token_provider': '',
  'column_types': '',
  'hide_url': 'No',
  'mimetype': None,
  'cache_url': None,
  'name': '2024_consum_electricitat_bcn.csv',
  'created': '2024-04-03T18:07:38.704596',
  'url': 'https://opendata-ajuntament.barcelona.cat/data/dataset/d9479057-781f-42b4-85e6-721bd0284130/resource/6f3a256a-dba6-46ac-88a4-546b93cb46da/download',
  'downloads_absolute': 643,
  'map_visualization_res': 'none',
  'qa': {'updated': '2026-08-18T02:06:54.310693',
   'openness_score': 3,
   'archival_timestamp': None,
   'format': 'CSV',
   'created': '2024-04-04T02:05:28.808034',
   'resource_timestamp': None,
   'openness_score_reason': 'This file had not been downloaded at the time of scoring it. URL extension "csv" relates to format "CSV" and receives score: 3.'},
  'last_modified': None,
  'position': 1,
  'revision_id': 'd4d7c26a-7689-417c-9fec-e1a2e51d4cf4',
  'resource_type': None},
 {'cache_last_updated': None,
  'token_type': '',
  'package_id': 'd9479057-781f-42b4-85e6-721bd0284130',
  'datastore_active': True,
  'id': '25caee3a-a9f2-4e1a-8c8b-1b5fcac4f152',
  'size': '14313373',
  'state': 'active',
  'api_access_number': 1007,
  'api_access_number_absolute': 1259,
  'token_required': 'No',
  'hash': '',
  'description': '',
  'format': 'CSV',
  'downloads': 757,
  'mimetype_inner': None,
  'url_type': '',
  'token_provider': '',
  'column_types': '',
  'hide_url': 'No',
  'mimetype': None,
  'cache_url': None,
  'name': '2023_consum_electricitat_bcn.csv',
  'created': '2023-04-17T08:23:40.327143',
  'url': 'https://opendata-ajuntament.barcelona.cat/data/dataset/d9479057-781f-42b4-85e6-721bd0284130/resource/25caee3a-a9f2-4e1a-8c8b-1b5fcac4f152/download',
  'downloads_absolute': 980,
  'map_visualization_res': 'none',
  'qa': {'updated': '2026-08-18T02:06:54.323394',
   'openness_score': 3,
   'archival_timestamp': None,
   'format': 'CSV',
   'created': '2023-04-18T02:04:20.157854',
   'resource_timestamp': None,
   'openness_score_reason': 'This file had not been downloaded at the time of scoring it. URL extension "csv" relates to format "CSV" and receives score: 3.'},
  'last_modified': '2024-01-09T18:17:18.707567',
  'position': 2,
  'revision_id': 'd4d7c26a-7689-417c-9fec-e1a2e51d4cf4',
  'resource_type': None},
 {'api_access_number_absolute': 1298,
  'cache_last_updated': None,
  'incorporated_in_cityos_res': 'No',
  'token_type': '',
  'package_id': 'd9479057-781f-42b4-85e6-721bd0284130',
  'datastore_active': True,
  'id': 'e685fa1a-9fbe-41a4-98a0-173464cd0c5f',
  'description': '',
  'state': 'active',
  'api_access_number': 1038,
  'size': '14947159',
  'token_required': 'No',
  'hash': '',
  'token_name': '',
  'format': 'CSV',
  'downloads': 705,
  'mimetype_inner': None,
  'url_type': '',
  'token_provider': '',
  'column_types': '[Integer, String, Integer, String, String, Integer]',
  'hide_url': 'No',
  'token_version': '',
  'mimetype': None,
  'cache_url': None,
  'name': '2022_consum_electricitat_bcn.csv',
  'created': '2022-12-21T13:15:22.059889',
  'url': 'https://opendata-ajuntament.barcelona.cat/data/dataset/d9479057-781f-42b4-85e6-721bd0284130/resource/e685fa1a-9fbe-41a4-98a0-173464cd0c5f/download',
  'downloads_absolute': 886,
  'map_visualization_res': 'none',
  'qa': {'updated': '2026-08-18T02:06:54.333135',
   'openness_score': 3,
   'archival_timestamp': None,
   'format': 'CSV',
   'created': '2022-12-22T02:06:18.613470',
   'resource_timestamp': None,
   'openness_score_reason': 'This file had not been downloaded at the time of scoring it. URL extension "csv" relates to format "CSV" and receives score: 3.'},
  'last_modified': '2026-05-06T11:22:58.696548',
  'position': 3,
  'revision_id': 'd4d7c26a-7689-417c-9fec-e1a2e51d4cf4',
  'resource_type': None},
 {'cache_last_updated': None,
  'token_type': '',
  'package_id': 'd9479057-781f-42b4-85e6-721bd0284130',
  'datastore_active': True,
  'id': '2b6ef2c2-cbd0-437c-a229-889e992e1dd6',
  'size': '14484539',
  'state': 'active',
  'api_access_number': 21,
  'api_access_number_absolute': 37,
  'token_required': 'No',
  'hash': '',
  'description': '',
  'format': 'CSV',
  'downloads': 733,
  'mimetype_inner': None,
  'url_type': '',
  'token_provider': '',
  'column_types': '',
  'hide_url': 'No',
  'mimetype': None,
  'cache_url': None,
  'name': '2021_consum_electricitat_bcn.csv',
  'created': '2022-12-19T08:31:19.568909',
  'url': 'https://opendata-ajuntament.barcelona.cat/data/dataset/d9479057-781f-42b4-85e6-721bd0284130/resource/2b6ef2c2-cbd0-437c-a229-889e992e1dd6/download',
  'downloads_absolute': 856,
  'map_visualization_res': 'none',
  'qa': {'updated': '2026-08-18T02:06:54.347605',
   'openness_score': 3,
   'archival_timestamp': None,
   'format': 'CSV',
   'created': '2022-12-20T02:06:19.766891',
   'resource_timestamp': None,
   'openness_score_reason': 'This file had not been downloaded at the time of scoring it. URL extension "csv" relates to format "CSV" and receives score: 3.'},
  'last_modified': '2023-12-14T12:59:54.783760',
  'position': 4,
  'revision_id': 'd4d7c26a-7689-417c-9fec-e1a2e51d4cf4',
  'resource_type': None},
 {'cache_last_updated': None,
  'token_type': '',
  'package_id': 'd9479057-781f-42b4-85e6-721bd0284130',
  'datastore_active': True,
  'id': '3c45a329-0414-4055-8f17-82456fc78dea',
  'size': '14574966',
  'state': 'active',
  'api_access_number': 12,
  'api_access_number_absolute': 22,
  'token_required': 'No',
  'hash': '',
  'description': '',
  'format': 'CSV',
  'downloads': 701,
  'mimetype_inner': None,
  'url_type': '',
  'token_provider': '',
  'column_types': '',
  'hide_url': 'No',
  'mimetype': None,
  'cache_url': None,
  'name': '2020_consum_electricitat_bcn.csv',
  'created': '2022-12-19T08:09:47.368630',
  'url': 'https://opendata-ajuntament.barcelona.cat/data/dataset/d9479057-781f-42b4-85e6-721bd0284130/resource/3c45a329-0414-4055-8f17-82456fc78dea/download',
  'downloads_absolute': 794,
  'map_visualization_res': 'none',
  'qa': {'updated': '2026-08-18T02:06:54.357909',
   'openness_score': 3,
   'archival_timestamp': None,
   'format': 'CSV',
   'created': '2022-12-20T02:06:19.750493',
   'resource_timestamp': None,
   'openness_score_reason': 'This file had not been downloaded at the time of scoring it. URL extension "csv" relates to format "CSV" and receives score: 3.'},
  'last_modified': '2023-12-14T12:58:48.376175',
  'position': 5,
  'revision_id': 'd4d7c26a-7689-417c-9fec-e1a2e51d4cf4',
  'resource_type': None},
 {'cache_last_updated': None,
  'token_type': '',
  'package_id': 'd9479057-781f-42b4-85e6-721bd0284130',
  'datastore_active': True,
  'id': '41b9a3e0-f079-4a4a-a8c3-670adc6bfb95',
  'size': '14590134',
  'state': 'active',
  'api_access_number': 12,
  'api_access_number_absolute': 22,
  'token_required': 'No',
  'hash': '',
  'description': '',
  'format': 'CSV',
  'downloads': 623,
  'mimetype_inner': None,
  'url_type': '',
  'token_provider': '',
  'column_types': '',
  'hide_url': 'No',
  'mimetype': None,
  'cache_url': None,
  'name': '2019_consum_electricitat_bcn.csv',
  'created': '2022-12-19T08:08:58.183306',
  'url': 'https://opendata-ajuntament.barcelona.cat/data/dataset/d9479057-781f-42b4-85e6-721bd0284130/resource/41b9a3e0-f079-4a4a-a8c3-670adc6bfb95/download',
  'downloads_absolute': 748,
  'map_visualization_res': 'none',
  'qa': {'updated': '2026-08-18T02:06:54.382929',
   'openness_score': 3,
   'archival_timestamp': None,
   'format': 'CSV',
   'created': '2022-12-20T02:06:19.729841',
   'resource_timestamp': None,
   'openness_score_reason': 'This file had not been downloaded at the time of scoring it. URL extension "csv" relates to format "CSV" and receives score: 3.'},
  'last_modified': '2024-02-06T17:33:57.021759',
  'position': 6,
  'revision_id': 'd4d7c26a-7689-417c-9fec-e1a2e51d4cf4',
  'resource_type': None}]

In [17]:
for resource in dataset["result"]["resources"]:
    print("Dataset name:", resource.get("name"))
    print("Format:", resource.get("format"))
    print("Resource ID:", resource.get("id"))
    print("URL:", resource.get("url"))
    print()

Dataset name: 2025_consum_electricitat_BCN.csv
Format: CSV
Resource ID: 635923fe-9e3b-40d3-857d-aaa9a6913531
URL: https://opendata-ajuntament.barcelona.cat/data/dataset/d9479057-781f-42b4-85e6-721bd0284130/resource/635923fe-9e3b-40d3-857d-aaa9a6913531/download

Dataset name: 2024_consum_electricitat_bcn.csv
Format: CSV
Resource ID: 6f3a256a-dba6-46ac-88a4-546b93cb46da
URL: https://opendata-ajuntament.barcelona.cat/data/dataset/d9479057-781f-42b4-85e6-721bd0284130/resource/6f3a256a-dba6-46ac-88a4-546b93cb46da/download

Dataset name: 2023_consum_electricitat_bcn.csv
Format: CSV
Resource ID: 25caee3a-a9f2-4e1a-8c8b-1b5fcac4f152
URL: https://opendata-ajuntament.barcelona.cat/data/dataset/d9479057-781f-42b4-85e6-721bd0284130/resource/25caee3a-a9f2-4e1a-8c8b-1b5fcac4f152/download

Dataset name: 2022_consum_electricitat_bcn.csv
Format: CSV
Resource ID: e685fa1a-9fbe-41a4-98a0-173464cd0c5f
URL: https://opendata-ajuntament.barcelona.cat/data/dataset/d9479057-781f-42b4-85e6-721bd0284130/resource/e685fa1a-9fbe-41a4-98a0-173464cd0c5f/download

Dataset name: 2021_consum_electricitat_bcn.csv
Format: CSV
Resource ID: 2b6ef2c2-cbd0-437c-a229-889e992e1dd6
URL: https://opendata-ajuntament.barcelona.cat/data/dataset/d9479057-781f-42b4-85e6-721bd0284130/resource/2b6ef2c2-cbd0-437c-a229-889e992e1dd6/download

Dataset name: 2020_consum_electricitat_bcn.csv
Format: CSV
Resource ID: 3c45a329-0414-4055-8f17-82456fc78dea
URL: https://opendata-ajuntament.barcelona.cat/data/dataset/d9479057-781f-42b4-85e6-721bd0284130/resource/3c45a329-0414-4055-8f17-82456fc78dea/download

Dataset name: 2019_consum_electricitat_bcn.csv
Format: CSV
Resource ID: 41b9a3e0-f079-4a4a-a8c3-670adc6bfb95
URL: https://opendata-ajuntament.barcelona.cat/data/dataset/d9479057-781f-42b4-85e6-721bd0284130/resource/41b9a3e0-f079-4a4a-a8c3-670adc6bfb95/download

In [18]:
# Nos quedamos sólo con aquellos recursos cuyo formato sea CSV o JSON
for resource in dataset["result"]["resources"]:
    
    if resource.get("format", "").upper() in ["CSV", "JSON"]:
        print(resource["name"])
        print(resource["format"])
        print(resource["id"])
        print()

2025_consum_electricitat_BCN.csv
CSV
635923fe-9e3b-40d3-857d-aaa9a6913531

2024_consum_electricitat_bcn.csv
CSV
6f3a256a-dba6-46ac-88a4-546b93cb46da

2023_consum_electricitat_bcn.csv
CSV
25caee3a-a9f2-4e1a-8c8b-1b5fcac4f152

2022_consum_electricitat_bcn.csv
CSV
e685fa1a-9fbe-41a4-98a0-173464cd0c5f

2021_consum_electricitat_bcn.csv
CSV
2b6ef2c2-cbd0-437c-a229-889e992e1dd6

2020_consum_electricitat_bcn.csv
CSV
3c45a329-0414-4055-8f17-82456fc78dea

2019_consum_electricitat_bcn.csv
CSV
41b9a3e0-f079-4a4a-a8c3-670adc6bfb95

In [19]:
# Con datastore_search realizamos una consulta para recuperar al menos 100 registros de un resource_id

url = base_url + "datastore_search"

for resource in dataset["result"]["resources"]:
    
    if resource.get("format", "").upper() in ["CSV", "JSON"]:

        resource_id = resource["id"]

        params = {
            "resource_id": resource_id,
            "limit": 100
        }

        response = requests.get(url, params=params)

        if response.status_code == 200:
            print(resource["name"])
            print(resource["format"])
            data = response.json()
            break

2024_consum_electricitat_bcn.csv
CSV

In [20]:
data["result"]["records"]

[{'Sector_Economic': 'Indústria',
  'Tram_Horari': 'De 00:00:00 a 05:59:59 h',
  'Codi_Postal': '8001',
  'Valor': '272',
  '_id': 1,
  'Data': '2024-01-01T00:00:00',
  'Any': '2024'},
 {'Sector_Economic': 'Indústria',
  'Tram_Horari': 'De 06:00:00 a 11:59:59 h',
  'Codi_Postal': '8001',
  'Valor': '350',
  '_id': 2,
  'Data': '2024-01-01T00:00:00',
  'Any': '2024'},
 {'Sector_Economic': 'Indústria',
  'Tram_Horari': 'De 12:00:00 a 17:59:59 h',
  'Codi_Postal': '8001',
  'Valor': '344',
  '_id': 3,
  'Data': '2024-01-01T00:00:00',
  'Any': '2024'},
 {'Sector_Economic': 'Indústria',
  'Tram_Horari': 'De 18:00:00 a 23:59:59 h',
  'Codi_Postal': '8001',
  'Valor': '309',
  '_id': 4,
  'Data': '2024-01-01T00:00:00',
  'Any': '2024'},
 {'Sector_Economic': 'Indústria',
  'Tram_Horari': 'No consta',
  'Codi_Postal': '8001',
  'Valor': '0',
  '_id': 5,
  'Data': '2024-01-01T00:00:00',
  'Any': '2024'},
 {'Sector_Economic': 'Residencial',
  'Tram_Horari': 'De 00:00:00 a 05:59:59 h',
  'Codi_Postal': '8001',
  'Valor': '27717',
  '_id': 6,
  'Data': '2024-01-01T00:00:00',
  'Any': '2024'},
 {'Sector_Economic': 'Residencial',
  'Tram_Horari': 'De 06:00:00 a 11:59:59 h',
  'Codi_Postal': '8001',
  'Valor': '33290',
  '_id': 7,
  'Data': '2024-01-01T00:00:00',
  'Any': '2024'},
 {'Sector_Economic': 'Residencial',
  'Tram_Horari': 'De 12:00:00 a 17:59:59 h',
  'Codi_Postal': '8001',
  'Valor': '46040',
  '_id': 8,
  'Data': '2024-01-01T00:00:00',
  'Any': '2024'},
 {'Sector_Economic': 'Residencial',
  'Tram_Horari': 'De 18:00:00 a 23:59:59 h',
  'Codi_Postal': '8001',
  'Valor': '48206',
  '_id': 9,
  'Data': '2024-01-01T00:00:00',
  'Any': '2024'},
 {'Sector_Economic': 'Residencial',
  'Tram_Horari': 'No consta',
  'Codi_Postal': '8001',
  'Valor': '0',
  '_id': 10,
  'Data': '2024-01-01T00:00:00',
  'Any': '2024'},
 {'Sector_Economic': 'Serveis',
  'Tram_Horari': 'De 00:00:00 a 05:59:59 h',
  'Codi_Postal': '8001',
  'Valor': '29807',
  '_id': 11,
  'Data': '2024-01-01T00:00:00',
  'Any': '2024'},
 {'Sector_Economic': 'Serveis',
  'Tram_Horari': 'De 06:00:00 a 11:59:59 h',
  'Codi_Postal': '8001',
  'Valor': '36812',
  '_id': 12,
  'Data': '2024-01-01T00:00:00',
  'Any': '2024'},
 {'Sector_Economic': 'Serveis',
  'Tram_Horari': 'De 12:00:00 a 17:59:59 h',
  'Codi_Postal': '8001',
  'Valor': '42174',
  '_id': 13,
  'Data': '2024-01-01T00:00:00',
  'Any': '2024'},
 {'Sector_Economic': 'Serveis',
  'Tram_Horari': 'De 18:00:00 a 23:59:59 h',
  'Codi_Postal': '8001',
  'Valor': '40234',
  '_id': 14,
  'Data': '2024-01-01T00:00:00',
  'Any': '2024'},
 {'Sector_Economic': 'Serveis',
  'Tram_Horari': 'No consta',
  'Codi_Postal': '8001',
  'Valor': '0',
  '_id': 15,
  'Data': '2024-01-01T00:00:00',
  'Any': '2024'},
 {'Sector_Economic': 'Indústria',
  'Tram_Horari': 'De 00:00:00 a 05:59:59 h',
  'Codi_Postal': '8002',
  'Valor': '796',
  '_id': 16,
  'Data': '2024-01-01T00:00:00',
  'Any': '2024'},
 {'Sector_Economic': 'Indústria',
  'Tram_Horari': 'De 06:00:00 a 11:59:59 h',
  'Codi_Postal': '8002',
  'Valor': '1050',
  '_id': 17,
  'Data': '2024-01-01T00:00:00',
  'Any': '2024'},
 {'Sector_Economic': 'Indústria',
  'Tram_Horari': 'De 12:00:00 a 17:59:59 h',
  'Codi_Postal': '8002',
  'Valor': '1172',
  '_id': 18,
  'Data': '2024-01-01T00:00:00',
  'Any': '2024'},
 {'Sector_Economic': 'Indústria',
  'Tram_Horari': 'De 18:00:00 a 23:59:59 h',
  'Codi_Postal': '8002',
  'Valor': '1055',
  '_id': 19,
  'Data': '2024-01-01T00:00:00',
  'Any': '2024'},
 {'Sector_Economic': 'Indústria',
  'Tram_Horari': 'No consta',
  'Codi_Postal': '8002',
  'Valor': '0',
  '_id': 20,
  'Data': '2024-01-01T00:00:00',
  'Any': '2024'},
 {'Sector_Economic': 'Residencial',
  'Tram_Horari': 'De 00:00:00 a 05:59:59 h',
  'Codi_Postal': '8002',
  'Valor': '22165',
  '_id': 21,
  'Data': '2024-01-01T00:00:00',
  'Any': '2024'},
 {'Sector_Economic': 'Residencial',
  'Tram_Horari': 'De 06:00:00 a 11:59:59 h',
  'Codi_Postal': '8002',
  'Valor': '25814',
  '_id': 22,
  'Data': '2024-01-01T00:00:00',
  'Any': '2024'},
 {'Sector_Economic': 'Residencial',
  'Tram_Horari': 'De 12:00:00 a 17:59:59 h',
  'Codi_Postal': '8002',
  'Valor': '33984',
  '_id': 23,
  'Data': '2024-01-01T00:00:00',
  'Any': '2024'},
 {'Sector_Economic': 'Residencial',
  'Tram_Horari': 'De 18:00:00 a 23:59:59 h',
  'Codi_Postal': '8002',
  'Valor': '35467',
  '_id': 24,
  'Data': '2024-01-01T00:00:00',
  'Any': '2024'},
 {'Sector_Economic': 'Residencial',
  'Tram_Horari': 'No consta',
  'Codi_Postal': '8002',
  'Valor': '0',
  '_id': 25,
  'Data': '2024-01-01T00:00:00',
  'Any': '2024'},
 {'Sector_Economic': 'Serveis',
  'Tram_Horari': 'De 00:00:00 a 05:59:59 h',
  'Codi_Postal': '8002',
  'Valor': '36933',
  '_id': 26,
  'Data': '2024-01-01T00:00:00',
  'Any': '2024'},
 {'Sector_Economic': 'Serveis',
  'Tram_Horari': 'De 06:00:00 a 11:59:59 h',
  'Codi_Postal': '8002',
  'Valor': '43490',
  '_id': 27,
  'Data': '2024-01-01T00:00:00',
  'Any': '2024'},
 {'Sector_Economic': 'Serveis',
  'Tram_Horari': 'De 12:00:00 a 17:59:59 h',
  'Codi_Postal': '8002',
  'Valor': '51798',
  '_id': 28,
  'Data': '2024-01-01T00:00:00',
  'Any': '2024'},
 {'Sector_Economic': 'Serveis',
  'Tram_Horari': 'De 18:00:00 a 23:59:59 h',
  'Codi_Postal': '8002',
  'Valor': '50113',
  '_id': 29,
  'Data': '2024-01-01T00:00:00',
  'Any': '2024'},
 {'Sector_Economic': 'Serveis',
  'Tram_Horari': 'No consta',
  'Codi_Postal': '8002',
  'Valor': '0',
  '_id': 30,
  'Data': '2024-01-01T00:00:00',
  'Any': '2024'},
 {'Sector_Economic': 'Indústria',
  'Tram_Horari': 'De 00:00:00 a 05:59:59 h',
  'Codi_Postal': '8003',
  'Valor': '548',
  '_id': 31,
  'Data': '2024-01-01T00:00:00',
  'Any': '2024'},
 {'Sector_Economic': 'Indústria',
  'Tram_Horari': 'De 06:00:00 a 11:59:59 h',
  'Codi_Postal': '8003',
  'Valor': '590',
  '_id': 32,
  'Data': '2024-01-01T00:00:00',
  'Any': '2024'},
 {'Sector_Economic': 'Indústria',
  'Tram_Horari': 'De 12:00:00 a 17:59:59 h',
  'Codi_Postal': '8003',
  'Valor': '642',
  '_id': 33,
  'Data': '2024-01-01T00:00:00',
  'Any': '2024'},
 {'Sector_Economic': 'Serveis',
  'Tram_Horari': 'No consta',
  'Codi_Postal': '8005',
  'Valor': '0',
  '_id': 705,
  'Data': '2024-01-02T00:00:00',
  'Any': '2024'},
 {'Sector_Economic': 'Indústria',
  'Tram_Horari': 'De 18:00:00 a 23:59:59 h',
  'Codi_Postal': '8003',
  'Valor': '585',
  '_id': 34,
  'Data': '2024-01-01T00:00:00',
  'Any': '2024'},
 {'Sector_Economic': 'Indústria',
  'Tram_Horari': 'No consta',
  'Codi_Postal': '8003',
  'Valor': '0',
  '_id': 35,
  'Data': '2024-01-01T00:00:00',
  'Any': '2024'},
 {'Sector_Economic': 'Residencial',
  'Tram_Horari': 'De 00:00:00 a 05:59:59 h',
  'Codi_Postal': '8003',
  'Valor': '31995',
  '_id': 36,
  'Data': '2024-01-01T00:00:00',
  'Any': '2024'},
 {'Sector_Economic': 'Residencial',
  'Tram_Horari': 'De 06:00:00 a 11:59:59 h',
  'Codi_Postal': '8003',
  'Valor': '38795',
  '_id': 37,
  'Data': '2024-01-01T00:00:00',
  'Any': '2024'},
 {'Sector_Economic': 'Residencial',
  'Tram_Horari': 'De 12:00:00 a 17:59:59 h',
  'Codi_Postal': '8003',
  'Valor': '52844',
  '_id': 38,
  'Data': '2024-01-01T00:00:00',
  'Any': '2024'},
 {'Sector_Economic': 'Residencial',
  'Tram_Horari': 'De 18:00:00 a 23:59:59 h',
  'Codi_Postal': '8003',
  'Valor': '55461',
  '_id': 39,
  'Data': '2024-01-01T00:00:00',
  'Any': '2024'},
 {'Sector_Economic': 'Residencial',
  'Tram_Horari': 'No consta',
  'Codi_Postal': '8003',
  'Valor': '0',
  '_id': 40,
  'Data': '2024-01-01T00:00:00',
  'Any': '2024'},
 {'Sector_Economic': 'Serveis',
  'Tram_Horari': 'De 00:00:00 a 05:59:59 h',
  'Codi_Postal': '8003',
  'Valor': '66643',
  '_id': 41,
  'Data': '2024-01-01T00:00:00',
  'Any': '2024'},
 {'Sector_Economic': 'Serveis',
  'Tram_Horari': 'De 06:00:00 a 11:59:59 h',
  'Codi_Postal': '8003',
  'Valor': '77722',
  '_id': 42,
  'Data': '2024-01-01T00:00:00',
  'Any': '2024'},
 {'Sector_Economic': 'Serveis',
  'Tram_Horari': 'De 12:00:00 a 17:59:59 h',
  'Codi_Postal': '8003',
  'Valor': '89079',
  '_id': 43,
  'Data': '2024-01-01T00:00:00',
  'Any': '2024'},
 {'Sector_Economic': 'Serveis',
  'Tram_Horari': 'De 18:00:00 a 23:59:59 h',
  'Codi_Postal': '8003',
  'Valor': '83505',
  '_id': 44,
  'Data': '2024-01-01T00:00:00',
  'Any': '2024'},
 {'Sector_Economic': 'Serveis',
  'Tram_Horari': 'No consta',
  'Codi_Postal': '8003',
  'Valor': '0',
  '_id': 45,
  'Data': '2024-01-01T00:00:00',
  'Any': '2024'},
 {'Sector_Economic': 'Indústria',
  'Tram_Horari': 'De 00:00:00 a 05:59:59 h',
  'Codi_Postal': '8004',
  'Valor': '4036',
  '_id': 46,
  'Data': '2024-01-01T00:00:00',
  'Any': '2024'},
 {'Sector_Economic': 'Indústria',
  'Tram_Horari': 'De 06:00:00 a 11:59:59 h',
  'Codi_Postal': '8004',
  'Valor': '4461',
  '_id': 47,
  'Data': '2024-01-01T00:00:00',
  'Any': '2024'},
 {'Sector_Economic': 'Indústria',
  'Tram_Horari': 'De 12:00:00 a 17:59:59 h',
  'Codi_Postal': '8004',
  'Valor': '4051',
  '_id': 48,
  'Data': '2024-01-01T00:00:00',
  'Any': '2024'},
 {'Sector_Economic': 'Indústria',
  'Tram_Horari': 'De 18:00:00 a 23:59:59 h',
  'Codi_Postal': '8004',
  'Valor': '4220',
  '_id': 49,
  'Data': '2024-01-01T00:00:00',
  'Any': '2024'},
 {'Sector_Economic': 'Indústria',
  'Tram_Horari': 'No consta',
  'Codi_Postal': '8004',
  'Valor': '0',
  '_id': 50,
  'Data': '2024-01-01T00:00:00',
  'Any': '2024'},
 {'Sector_Economic': 'Residencial',
  'Tram_Horari': 'De 00:00:00 a 05:59:59 h',
  'Codi_Postal': '8004',
  'Valor': '26663',
  '_id': 51,
  'Data': '2024-01-01T00:00:00',
  'Any': '2024'},
 {'Sector_Economic': 'Residencial',
  'Tram_Horari': 'De 06:00:00 a 11:59:59 h',
  'Codi_Postal': '8004',
  'Valor': '32853',
  '_id': 52,
  'Data': '2024-01-01T00:00:00',
  'Any': '2024'},
 {'Sector_Economic': 'Residencial',
  'Tram_Horari': 'De 12:00:00 a 17:59:59 h',
  'Codi_Postal': '8004',
  'Valor': '46064',
  '_id': 53,
  'Data': '2024-01-01T00:00:00',
  'Any': '2024'},
 {'Sector_Economic': 'Residencial',
  'Tram_Horari': 'De 18:00:00 a 23:59:59 h',
  'Codi_Postal': '8004',
  'Valor': '50169',
  '_id': 54,
  'Data': '2024-01-01T00:00:00',
  'Any': '2024'},
 {'Sector_Economic': 'Residencial',
  'Tram_Horari': 'No consta',
  'Codi_Postal': '8004',
  'Valor': '0',
  '_id': 55,
  'Data': '2024-01-01T00:00:00',
  'Any': '2024'},
 {'Sector_Economic': 'Serveis',
  'Tram_Horari': 'De 00:00:00 a 05:59:59 h',
  'Codi_Postal': '8004',
  'Valor': '27742',
  '_id': 56,
  'Data': '2024-01-01T00:00:00',
  'Any': '2024'},
 {'Sector_Economic': 'Serveis',
  'Tram_Horari': 'De 06:00:00 a 11:59:59 h',
  'Codi_Postal': '8004',
  'Valor': '29736',
  '_id': 57,
  'Data': '2024-01-01T00:00:00',
  'Any': '2024'},
 {'Sector_Economic': 'Serveis',
  'Tram_Horari': 'De 12:00:00 a 17:59:59 h',
  'Codi_Postal': '8004',
  'Valor': '31789',
  '_id': 58,
  'Data': '2024-01-01T00:00:00',
  'Any': '2024'},
 {'Sector_Economic': 'Serveis',
  'Tram_Horari': 'De 18:00:00 a 23:59:59 h',
  'Codi_Postal': '8004',
  'Valor': '31785',
  '_id': 59,
  'Data': '2024-01-01T00:00:00',
  'Any': '2024'},
 {'Sector_Economic': 'Serveis',
  'Tram_Horari': 'No consta',
  'Codi_Postal': '8004',
  'Valor': '0',
  '_id': 60,
  'Data': '2024-01-01T00:00:00',
  'Any': '2024'},
 {'Sector_Economic': 'Indústria',
  'Tram_Horari': 'De 00:00:00 a 05:59:59 h',
  'Codi_Postal': '8005',
  'Valor': '1403',
  '_id': 61,
  'Data': '2024-01-01T00:00:00',
  'Any': '2024'},
 {'Sector_Economic': 'Indústria',
  'Tram_Horari': 'De 06:00:00 a 11:59:59 h',
  'Codi_Postal': '8005',
  'Valor': '1813',
  '_id': 62,
  'Data': '2024-01-01T00:00:00',
  'Any': '2024'},
 {'Sector_Economic': 'Indústria',
  'Tram_Horari': 'De 12:00:00 a 17:59:59 h',
  'Codi_Postal': '8005',
  'Valor': '1941',
  '_id': 63,
  'Data': '2024-01-01T00:00:00',
  'Any': '2024'},
 {'Sector_Economic': 'Indústria',
  'Tram_Horari': 'De 18:00:00 a 23:59:59 h',
  'Codi_Postal': '8005',
  'Valor': '1776',
  '_id': 64,
  'Data': '2024-01-01T00:00:00',
  'Any': '2024'},
 {'Sector_Economic': 'Indústria',
  'Tram_Horari': 'No consta',
  'Codi_Postal': '8005',
  'Valor': '0',
  '_id': 65,
  'Data': '2024-01-01T00:00:00',
  'Any': '2024'},
 {'Sector_Economic': 'Residencial',
  'Tram_Horari': 'De 00:00:00 a 05:59:59 h',
  'Codi_Postal': '8005',
  'Valor': '29188',
  '_id': 66,
  'Data': '2024-01-01T00:00:00',
  'Any': '2024'},
 {'Sector_Economic': 'Residencial',
  'Tram_Horari': 'De 06:00:00 a 11:59:59 h',
  'Codi_Postal': '8005',
  'Valor': '37187',
  '_id': 67,
  'Data': '2024-01-01T00:00:00',
  'Any': '2024'},
 {'Sector_Economic': 'Residencial',
  'Tram_Horari': 'De 12:00:00 a 17:59:59 h',
  'Codi_Postal': '8005',
  'Valor': '47764',
  '_id': 68,
  'Data': '2024-01-01T00:00:00',
  'Any': '2024'},
 {'Sector_Economic': 'Residencial',
  'Tram_Horari': 'De 18:00:00 a 23:59:59 h',
  'Codi_Postal': '8005',
  'Valor': '50804',
  '_id': 69,
  'Data': '2024-01-01T00:00:00',
  'Any': '2024'},
 {'Sector_Economic': 'Residencial',
  'Tram_Horari': 'No consta',
  'Codi_Postal': '8005',
  'Valor': '0',
  '_id': 70,
  'Data': '2024-01-01T00:00:00',
  'Any': '2024'},
 {'Sector_Economic': 'Serveis',
  'Tram_Horari': 'De 00:00:00 a 05:59:59 h',
  'Codi_Postal': '8005',
  'Valor': '58288',
  '_id': 71,
  'Data': '2024-01-01T00:00:00',
  'Any': '2024'},
 {'Sector_Economic': 'Serveis',
  'Tram_Horari': 'De 06:00:00 a 11:59:59 h',
  'Codi_Postal': '8005',
  'Valor': '64919',
  '_id': 72,
  'Data': '2024-01-01T00:00:00',
  'Any': '2024'},
 {'Sector_Economic': 'Serveis',
  'Tram_Horari': 'De 12:00:00 a 17:59:59 h',
  'Codi_Postal': '8005',
  'Valor': '70381',
  '_id': 73,
  'Data': '2024-01-01T00:00:00',
  'Any': '2024'},
 {'Sector_Economic': 'Serveis',
  'Tram_Horari': 'De 18:00:00 a 23:59:59 h',
  'Codi_Postal': '8005',
  'Valor': '68253',
  '_id': 74,
  'Data': '2024-01-01T00:00:00',
  'Any': '2024'},
 {'Sector_Economic': 'Serveis',
  'Tram_Horari': 'No consta',
  'Codi_Postal': '8005',
  'Valor': '0',
  '_id': 75,
  'Data': '2024-01-01T00:00:00',
  'Any': '2024'},
 {'Sector_Economic': 'Indústria',
  'Tram_Horari': 'De 00:00:00 a 05:59:59 h',
  'Codi_Postal': '8006',
  'Valor': '567',
  '_id': 76,
  'Data': '2024-01-01T00:00:00',
  'Any': '2024'},
 {'Sector_Economic': 'Indústria',
  'Tram_Horari': 'De 06:00:00 a 11:59:59 h',
  'Codi_Postal': '8006',
  'Valor': '704',
  '_id': 77,
  'Data': '2024-01-01T00:00:00',
  'Any': '2024'},
 {'Sector_Economic': 'Indústria',
  'Tram_Horari': 'De 12:00:00 a 17:59:59 h',
  'Codi_Postal': '8006',
  'Valor': '692',
  '_id': 78,
  'Data': '2024-01-01T00:00:00',
  'Any': '2024'},
 {'Sector_Economic': 'Indústria',
  'Tram_Horari': 'De 18:00:00 a 23:59:59 h',
  'Codi_Postal': '8006',
  'Valor': '647',
  '_id': 79,
  'Data': '2024-01-01T00:00:00',
  'Any': '2024'},
 {'Sector_Economic': 'Indústria',
  'Tram_Horari': 'No consta',
  'Codi_Postal': '8006',
  'Valor': '0',
  '_id': 80,
  'Data': '2024-01-01T00:00:00',
  'Any': '2024'},
 {'Sector_Economic': 'Residencial',
  'Tram_Horari': 'De 00:00:00 a 05:59:59 h',
  'Codi_Postal': '8006',
  'Valor': '34711',
  '_id': 81,
  'Data': '2024-01-01T00:00:00',
  'Any': '2024'},
 {'Sector_Economic': 'Residencial',
  'Tram_Horari': 'De 06:00:00 a 11:59:59 h',
  'Codi_Postal': '8006',
  'Valor': '43092',
  '_id': 82,
  'Data': '2024-01-01T00:00:00',
  'Any': '2024'},
 {'Sector_Economic': 'Residencial',
  'Tram_Horari': 'De 12:00:00 a 17:59:59 h',
  'Codi_Postal': '8006',
  'Valor': '57099',
  '_id': 83,
  'Data': '2024-01-01T00:00:00',
  'Any': '2024'},
 {'Sector_Economic': 'Residencial',
  'Tram_Horari': 'De 18:00:00 a 23:59:59 h',
  'Codi_Postal': '8006',
  'Valor': '61474',
  '_id': 84,
  'Data': '2024-01-01T00:00:00',
  'Any': '2024'},
 {'Sector_Economic': 'Residencial',
  'Tram_Horari': 'No consta',
  'Codi_Postal': '8006',
  'Valor': '0',
  '_id': 85,
  'Data': '2024-01-01T00:00:00',
  'Any': '2024'},
 {'Sector_Economic': 'Serveis',
  'Tram_Horari': 'De 00:00:00 a 05:59:59 h',
  'Codi_Postal': '8006',
  'Valor': '38885',
  '_id': 86,
  'Data': '2024-01-01T00:00:00',
  'Any': '2024'},
 {'Sector_Economic': 'Serveis',
  'Tram_Horari': 'De 06:00:00 a 11:59:59 h',
  'Codi_Postal': '8006',
  'Valor': '46150',
  '_id': 87,
  'Data': '2024-01-01T00:00:00',
  'Any': '2024'},
 {'Sector_Economic': 'Serveis',
  'Tram_Horari': 'De 12:00:00 a 17:59:59 h',
  'Codi_Postal': '8006',
  'Valor': '49549',
  '_id': 88,
  'Data': '2024-01-01T00:00:00',
  'Any': '2024'},
 {'Sector_Economic': 'Serveis',
  'Tram_Horari': 'De 18:00:00 a 23:59:59 h',
  'Codi_Postal': '8006',
  'Valor': '46104',
  '_id': 89,
  'Data': '2024-01-01T00:00:00',
  'Any': '2024'},
 {'Sector_Economic': 'Serveis',
  'Tram_Horari': 'No consta',
  'Codi_Postal': '8006',
  'Valor': '0',
  '_id': 90,
  'Data': '2024-01-01T00:00:00',
  'Any': '2024'},
 {'Sector_Economic': 'Indústria',
  'Tram_Horari': 'De 00:00:00 a 05:59:59 h',
  'Codi_Postal': '8007',
  'Valor': '302',
  '_id': 91,
  'Data': '2024-01-01T00:00:00',
  'Any': '2024'},
 {'Sector_Economic': 'Indústria',
  'Tram_Horari': 'De 06:00:00 a 11:59:59 h',
  'Codi_Postal': '8007',
  'Valor': '472',
  '_id': 92,
  'Data': '2024-01-01T00:00:00',
  'Any': '2024'},
 {'Sector_Economic': 'Indústria',
  'Tram_Horari': 'De 12:00:00 a 17:59:59 h',
  'Codi_Postal': '8007',
  'Valor': '538',
  '_id': 93,
  'Data': '2024-01-01T00:00:00',
  'Any': '2024'},
 {'Sector_Economic': 'Indústria',
  'Tram_Horari': 'De 18:00:00 a 23:59:59 h',
  'Codi_Postal': '8007',
  'Valor': '426',
  '_id': 94,
  'Data': '2024-01-01T00:00:00',
  'Any': '2024'},
 {'Sector_Economic': 'Indústria',
  'Tram_Horari': 'No consta',
  'Codi_Postal': '8007',
  'Valor': '0',
  '_id': 95,
  'Data': '2024-01-01T00:00:00',
  'Any': '2024'},
 {'Sector_Economic': 'Residencial',
  'Tram_Horari': 'De 00:00:00 a 05:59:59 h',
  'Codi_Postal': '8007',
  'Valor': '10851',
  '_id': 96,
  'Data': '2024-01-01T00:00:00',
  'Any': '2024'},
 {'Sector_Economic': 'Residencial',
  'Tram_Horari': 'De 06:00:00 a 11:59:59 h',
  'Codi_Postal': '8007',
  'Valor': '13348',
  '_id': 97,
  'Data': '2024-01-01T00:00:00',
  'Any': '2024'},
 {'Sector_Economic': 'Residencial',
  'Tram_Horari': 'De 12:00:00 a 17:59:59 h',
  'Codi_Postal': '8007',
  'Valor': '15964',
  '_id': 98,
  'Data': '2024-01-01T00:00:00',
  'Any': '2024'},
 {'Sector_Economic': 'Residencial',
  'Tram_Horari': 'De 18:00:00 a 23:59:59 h',
  'Codi_Postal': '8007',
  'Valor': '16073',
  '_id': 99,
  'Data': '2024-01-01T00:00:00',
  'Any': '2024'}]

In [21]:
# Convertimos el resultado a un DataFrame
df = pd.DataFrame(data["result"]["records"])

df.head()

,Sector_Economic,Tram_Horari,Codi_Postal,Valor,_id,Data,Any
0,Indústria,De 00:00:00 a 05:59:59 h,8001,272,1,2024-01-01T00:00:00,2024
1,Indústria,De 06:00:00 a 11:59:59 h,8001,350,2,2024-01-01T00:00:00,2024
2,Indústria,De 12:00:00 a 17:59:59 h,8001,344,3,2024-01-01T00:00:00,2024
3,Indústria,De 18:00:00 a 23:59:59 h,8001,309,4,2024-01-01T00:00:00,2024
4,Indústria,No consta,8001,0,5,2024-01-01T00:00:00,2024

In [22]:
# Convertimos el DataFrame a un fichero .csv

df.to_csv("dataset_2024_consum_electricitat_bcn.csv", index=False)